// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package expire
type ExpirePostResponse_data_outcome int

const (
    EXPIRED_EXPIREPOSTRESPONSE_DATA_OUTCOME ExpirePostResponse_data_outcome = iota
)

func (i ExpirePostResponse_data_outcome) String() string {
    return []string{"expired"}[i]
}
func ParseExpirePostResponse_data_outcome(v string) (any, error) {
    result := EXPIRED_EXPIREPOSTRESPONSE_DATA_OUTCOME
    switch v {
        case "expired":
            result = EXPIRED_EXPIREPOSTRESPONSE_DATA_OUTCOME
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeExpirePostResponse_data_outcome(values []ExpirePostResponse_data_outcome) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i ExpirePostResponse_data_outcome) isMultiValue() bool {
    return false
}
