// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1DocumentsItemSubmissionsItemExpireRequestBuilder builds and executes requests for operations under \api\v1\documents\{id}\submissions\{sid}\expire
type V1DocumentsItemSubmissionsItemExpireRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1DocumentsItemSubmissionsItemExpireRequestBuilderInternal instantiates a new V1DocumentsItemSubmissionsItemExpireRequestBuilder and sets the default values.
func NewV1DocumentsItemSubmissionsItemExpireRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemSubmissionsItemExpireRequestBuilder) {
    m := &V1DocumentsItemSubmissionsItemExpireRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v1/documents/{id}/submissions/{sid}/expire", pathParameters),
    }
    return m
}
// NewV1DocumentsItemSubmissionsItemExpireRequestBuilder instantiates a new V1DocumentsItemSubmissionsItemExpireRequestBuilder and sets the default values.
func NewV1DocumentsItemSubmissionsItemExpireRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemSubmissionsItemExpireRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1DocumentsItemSubmissionsItemExpireRequestBuilderInternal(urlParams, requestAdapter)
}
// Post requires submissions:write. Immediately expires all active links on a completely unsigned, unsealed submission. Retains answers, consent and audit evidence. Repeating the request is safe. Completed or partially signed submissions and active send capabilities remain protected.
// returns a V1DocumentsItemSubmissionsItemExpirePostResponseable when successful
// returns a V1DocumentsItemSubmissionsItemExpire400Error error when the service returns a 400 status code
// returns a V1DocumentsItemSubmissionsItemExpire403Error error when the service returns a 403 status code
// returns a V1DocumentsItemSubmissionsItemExpire404Error error when the service returns a 404 status code
// returns a V1DocumentsItemSubmissionsItemExpire409Error error when the service returns a 409 status code
func (m *V1DocumentsItemSubmissionsItemExpireRequestBuilder) Post(ctx context.Context, body V1DocumentsItemSubmissionsItemExpirePostRequestBodyable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(V1DocumentsItemSubmissionsItemExpirePostResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": CreateV1DocumentsItemSubmissionsItemExpire400ErrorFromDiscriminatorValue,
        "403": CreateV1DocumentsItemSubmissionsItemExpire403ErrorFromDiscriminatorValue,
        "404": CreateV1DocumentsItemSubmissionsItemExpire404ErrorFromDiscriminatorValue,
        "409": CreateV1DocumentsItemSubmissionsItemExpire409ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateV1DocumentsItemSubmissionsItemExpirePostResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(V1DocumentsItemSubmissionsItemExpirePostResponseable), nil
}
// ToPostRequestInformation requires submissions:write. Immediately expires all active links on a completely unsigned, unsealed submission. Retains answers, consent and audit evidence. Repeating the request is safe. Completed or partially signed submissions and active send capabilities remain protected.
// returns a *RequestInformation when successful
func (m *V1DocumentsItemSubmissionsItemExpireRequestBuilder) ToPostRequestInformation(ctx context.Context, body V1DocumentsItemSubmissionsItemExpirePostRequestBodyable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1DocumentsItemSubmissionsItemExpireRequestBuilder when successful
func (m *V1DocumentsItemSubmissionsItemExpireRequestBuilder) WithUrl(rawUrl string)(*V1DocumentsItemSubmissionsItemExpireRequestBuilder) {
    return NewV1DocumentsItemSubmissionsItemExpireRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
