// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type V1DeliveriesGetResponse_data struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The attemptedAt property
    attemptedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The blockedReason property
    blockedReason *string
    // The channel property
    channel *string
    // The eventType property
    eventType *string
    // The id property
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The profile property
    profile V1DeliveriesGetResponse_data_profileable
    // The providerStatus property
    providerStatus *string
    // The requestAccepted property
    requestAccepted *bool
    // The state property
    state *string
    // The statusCode property
    statusCode *int32
    // For email and WhatsApp, whether the provider accepted the request. This does not establish inbox delivery; inspect state and providerStatus.
    success *bool
}
// NewV1DeliveriesGetResponse_data instantiates a new V1DeliveriesGetResponse_data and sets the default values.
func NewV1DeliveriesGetResponse_data()(*V1DeliveriesGetResponse_data) {
    m := &V1DeliveriesGetResponse_data{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateV1DeliveriesGetResponse_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1DeliveriesGetResponse_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1DeliveriesGetResponse_data(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *V1DeliveriesGetResponse_data) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAttemptedAt gets the attemptedAt property value. The attemptedAt property
// returns a *Time when successful
func (m *V1DeliveriesGetResponse_data) GetAttemptedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.attemptedAt
}
// GetBlockedReason gets the blockedReason property value. The blockedReason property
// returns a *string when successful
func (m *V1DeliveriesGetResponse_data) GetBlockedReason()(*string) {
    return m.blockedReason
}
// GetChannel gets the channel property value. The channel property
// returns a *string when successful
func (m *V1DeliveriesGetResponse_data) GetChannel()(*string) {
    return m.channel
}
// GetEventType gets the eventType property value. The eventType property
// returns a *string when successful
func (m *V1DeliveriesGetResponse_data) GetEventType()(*string) {
    return m.eventType
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *V1DeliveriesGetResponse_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["attemptedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAttemptedAt(val)
        }
        return nil
    }
    res["blockedReason"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBlockedReason(val)
        }
        return nil
    }
    res["channel"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetChannel(val)
        }
        return nil
    }
    res["eventType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEventType(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["profile"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateV1DeliveriesGetResponse_data_profileFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProfile(val.(V1DeliveriesGetResponse_data_profileable))
        }
        return nil
    }
    res["providerStatus"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProviderStatus(val)
        }
        return nil
    }
    res["requestAccepted"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRequestAccepted(val)
        }
        return nil
    }
    res["state"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetState(val)
        }
        return nil
    }
    res["statusCode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatusCode(val)
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *UUID when successful
func (m *V1DeliveriesGetResponse_data) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetProfile gets the profile property value. The profile property
// returns a V1DeliveriesGetResponse_data_profileable when successful
func (m *V1DeliveriesGetResponse_data) GetProfile()(V1DeliveriesGetResponse_data_profileable) {
    return m.profile
}
// GetProviderStatus gets the providerStatus property value. The providerStatus property
// returns a *string when successful
func (m *V1DeliveriesGetResponse_data) GetProviderStatus()(*string) {
    return m.providerStatus
}
// GetRequestAccepted gets the requestAccepted property value. The requestAccepted property
// returns a *bool when successful
func (m *V1DeliveriesGetResponse_data) GetRequestAccepted()(*bool) {
    return m.requestAccepted
}
// GetState gets the state property value. The state property
// returns a *string when successful
func (m *V1DeliveriesGetResponse_data) GetState()(*string) {
    return m.state
}
// GetStatusCode gets the statusCode property value. The statusCode property
// returns a *int32 when successful
func (m *V1DeliveriesGetResponse_data) GetStatusCode()(*int32) {
    return m.statusCode
}
// GetSuccess gets the success property value. For email and WhatsApp, whether the provider accepted the request. This does not establish inbox delivery; inspect state and providerStatus.
// returns a *bool when successful
func (m *V1DeliveriesGetResponse_data) GetSuccess()(*bool) {
    return m.success
}
// Serialize serializes information the current object
func (m *V1DeliveriesGetResponse_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteTimeValue("attemptedAt", m.GetAttemptedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("blockedReason", m.GetBlockedReason())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("channel", m.GetChannel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("eventType", m.GetEventType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("profile", m.GetProfile())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("providerStatus", m.GetProviderStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("requestAccepted", m.GetRequestAccepted())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("state", m.GetState())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("statusCode", m.GetStatusCode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *V1DeliveriesGetResponse_data) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAttemptedAt sets the attemptedAt property value. The attemptedAt property
func (m *V1DeliveriesGetResponse_data) SetAttemptedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.attemptedAt = value
}
// SetBlockedReason sets the blockedReason property value. The blockedReason property
func (m *V1DeliveriesGetResponse_data) SetBlockedReason(value *string)() {
    m.blockedReason = value
}
// SetChannel sets the channel property value. The channel property
func (m *V1DeliveriesGetResponse_data) SetChannel(value *string)() {
    m.channel = value
}
// SetEventType sets the eventType property value. The eventType property
func (m *V1DeliveriesGetResponse_data) SetEventType(value *string)() {
    m.eventType = value
}
// SetId sets the id property value. The id property
func (m *V1DeliveriesGetResponse_data) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetProfile sets the profile property value. The profile property
func (m *V1DeliveriesGetResponse_data) SetProfile(value V1DeliveriesGetResponse_data_profileable)() {
    m.profile = value
}
// SetProviderStatus sets the providerStatus property value. The providerStatus property
func (m *V1DeliveriesGetResponse_data) SetProviderStatus(value *string)() {
    m.providerStatus = value
}
// SetRequestAccepted sets the requestAccepted property value. The requestAccepted property
func (m *V1DeliveriesGetResponse_data) SetRequestAccepted(value *bool)() {
    m.requestAccepted = value
}
// SetState sets the state property value. The state property
func (m *V1DeliveriesGetResponse_data) SetState(value *string)() {
    m.state = value
}
// SetStatusCode sets the statusCode property value. The statusCode property
func (m *V1DeliveriesGetResponse_data) SetStatusCode(value *int32)() {
    m.statusCode = value
}
// SetSuccess sets the success property value. For email and WhatsApp, whether the provider accepted the request. This does not establish inbox delivery; inspect state and providerStatus.
func (m *V1DeliveriesGetResponse_data) SetSuccess(value *bool)() {
    m.success = value
}
type V1DeliveriesGetResponse_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAttemptedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetBlockedReason()(*string)
    GetChannel()(*string)
    GetEventType()(*string)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetProfile()(V1DeliveriesGetResponse_data_profileable)
    GetProviderStatus()(*string)
    GetRequestAccepted()(*bool)
    GetState()(*string)
    GetStatusCode()(*int32)
    GetSuccess()(*bool)
    SetAttemptedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetBlockedReason(value *string)()
    SetChannel(value *string)()
    SetEventType(value *string)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetProfile(value V1DeliveriesGetResponse_data_profileable)()
    SetProviderStatus(value *string)()
    SetRequestAccepted(value *bool)()
    SetState(value *string)()
    SetStatusCode(value *int32)()
    SetSuccess(value *bool)()
}
