// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f "client/models"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1DocumentsItemParseJobsWithJobItemRequestBuilder builds and executes requests for operations under \api\v1\documents\{id}\parse-jobs\{jobId}
type V1DocumentsItemParseJobsWithJobItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Apply the apply property
// returns a *V1DocumentsItemParseJobsItemApplyRequestBuilder when successful
func (m *V1DocumentsItemParseJobsWithJobItemRequestBuilder) Apply()(*V1DocumentsItemParseJobsItemApplyRequestBuilder) {
    return NewV1DocumentsItemParseJobsItemApplyRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewV1DocumentsItemParseJobsWithJobItemRequestBuilderInternal instantiates a new V1DocumentsItemParseJobsWithJobItemRequestBuilder and sets the default values.
func NewV1DocumentsItemParseJobsWithJobItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemParseJobsWithJobItemRequestBuilder) {
    m := &V1DocumentsItemParseJobsWithJobItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v1/documents/{id}/parse-jobs/{jobId}", pathParameters),
    }
    return m
}
// NewV1DocumentsItemParseJobsWithJobItemRequestBuilder instantiates a new V1DocumentsItemParseJobsWithJobItemRequestBuilder and sets the default values.
func NewV1DocumentsItemParseJobsWithJobItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemParseJobsWithJobItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1DocumentsItemParseJobsWithJobItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get document parse job status
// returns a GetDocumentParseJobResponseable when successful
// returns a V1DocumentsItemParseJobsItemGetDocumentParseJobResponse404Error error when the service returns a 404 status code
func (m *V1DocumentsItemParseJobsWithJobItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.GetDocumentParseJobResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "404": CreateV1DocumentsItemParseJobsItemGetDocumentParseJobResponse404ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.CreateGetDocumentParseJobResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.GetDocumentParseJobResponseable), nil
}
// ToGetRequestInformation get document parse job status
// returns a *RequestInformation when successful
func (m *V1DocumentsItemParseJobsWithJobItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1DocumentsItemParseJobsWithJobItemRequestBuilder when successful
func (m *V1DocumentsItemParseJobsWithJobItemRequestBuilder) WithUrl(rawUrl string)(*V1DocumentsItemParseJobsWithJobItemRequestBuilder) {
    return NewV1DocumentsItemParseJobsWithJobItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
