// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type V1DocumentsItemSignerRolesItemWithRPutRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The color property
    color *string
    // The label property
    label *string
    // The order property
    order *int32
    // The role property
    role *string
}
// NewV1DocumentsItemSignerRolesItemWithRPutRequestBody instantiates a new V1DocumentsItemSignerRolesItemWithRPutRequestBody and sets the default values.
func NewV1DocumentsItemSignerRolesItemWithRPutRequestBody()(*V1DocumentsItemSignerRolesItemWithRPutRequestBody) {
    m := &V1DocumentsItemSignerRolesItemWithRPutRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateV1DocumentsItemSignerRolesItemWithRPutRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1DocumentsItemSignerRolesItemWithRPutRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1DocumentsItemSignerRolesItemWithRPutRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetColor gets the color property value. The color property
// returns a *string when successful
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) GetColor()(*string) {
    return m.color
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["color"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetColor(val)
        }
        return nil
    }
    res["label"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLabel(val)
        }
        return nil
    }
    res["order"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOrder(val)
        }
        return nil
    }
    res["role"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRole(val)
        }
        return nil
    }
    return res
}
// GetLabel gets the label property value. The label property
// returns a *string when successful
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) GetLabel()(*string) {
    return m.label
}
// GetOrder gets the order property value. The order property
// returns a *int32 when successful
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) GetOrder()(*int32) {
    return m.order
}
// GetRole gets the role property value. The role property
// returns a *string when successful
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) GetRole()(*string) {
    return m.role
}
// Serialize serializes information the current object
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("color", m.GetColor())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("label", m.GetLabel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("order", m.GetOrder())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("role", m.GetRole())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetColor sets the color property value. The color property
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) SetColor(value *string)() {
    m.color = value
}
// SetLabel sets the label property value. The label property
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) SetLabel(value *string)() {
    m.label = value
}
// SetOrder sets the order property value. The order property
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) SetOrder(value *int32)() {
    m.order = value
}
// SetRole sets the role property value. The role property
func (m *V1DocumentsItemSignerRolesItemWithRPutRequestBody) SetRole(value *string)() {
    m.role = value
}
type V1DocumentsItemSignerRolesItemWithRPutRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetColor()(*string)
    GetLabel()(*string)
    GetOrder()(*int32)
    GetRole()(*string)
    SetColor(value *string)()
    SetLabel(value *string)()
    SetOrder(value *int32)()
    SetRole(value *string)()
}
