// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1DocumentsItemSignerRolesWithRItemRequestBuilder builds and executes requests for operations under \api\v1\documents\{id}\signer-roles\{rid}
type V1DocumentsItemSignerRolesWithRItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1DocumentsItemSignerRolesWithRItemRequestBuilderInternal instantiates a new V1DocumentsItemSignerRolesWithRItemRequestBuilder and sets the default values.
func NewV1DocumentsItemSignerRolesWithRItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemSignerRolesWithRItemRequestBuilder) {
    m := &V1DocumentsItemSignerRolesWithRItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v1/documents/{id}/signer-roles/{rid}", pathParameters),
    }
    return m
}
// NewV1DocumentsItemSignerRolesWithRItemRequestBuilder instantiates a new V1DocumentsItemSignerRolesWithRItemRequestBuilder and sets the default values.
func NewV1DocumentsItemSignerRolesWithRItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemSignerRolesWithRItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1DocumentsItemSignerRolesWithRItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete delete a signer role
// returns a V1DocumentsItemSignerRolesItemWithRDeleteResponseable when successful
func (m *V1DocumentsItemSignerRolesWithRItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(V1DocumentsItemSignerRolesItemWithRDeleteResponseable, error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateV1DocumentsItemSignerRolesItemWithRDeleteResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(V1DocumentsItemSignerRolesItemWithRDeleteResponseable), nil
}
// ToDeleteRequestInformation delete a signer role
// returns a *RequestInformation when successful
func (m *V1DocumentsItemSignerRolesWithRItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1DocumentsItemSignerRolesWithRItemRequestBuilder when successful
func (m *V1DocumentsItemSignerRolesWithRItemRequestBuilder) WithUrl(rawUrl string)(*V1DocumentsItemSignerRolesWithRItemRequestBuilder) {
    return NewV1DocumentsItemSignerRolesWithRItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
