// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type V1DocumentsItemFieldsItemWithFPutRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The assigneeRole property
    assigneeRole *string
    // The defaultValue property
    defaultValue *string
    // The height property
    height *float64
    // The isReadOnly property
    isReadOnly *bool
    // The isRequired property
    isRequired *bool
    // The label property
    label *string
    // The options property
    options V1DocumentsItemFieldsItemWithFPutRequestBody_optionsable
    // The order property
    order *int32
    // The pageNumber property
    pageNumber *int32
    // The width property
    width *float64
    // The x property
    x *float64
    // The y property
    y *float64
}
// NewV1DocumentsItemFieldsItemWithFPutRequestBody instantiates a new V1DocumentsItemFieldsItemWithFPutRequestBody and sets the default values.
func NewV1DocumentsItemFieldsItemWithFPutRequestBody()(*V1DocumentsItemFieldsItemWithFPutRequestBody) {
    m := &V1DocumentsItemFieldsItemWithFPutRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateV1DocumentsItemFieldsItemWithFPutRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1DocumentsItemFieldsItemWithFPutRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1DocumentsItemFieldsItemWithFPutRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAssigneeRole gets the assigneeRole property value. The assigneeRole property
// returns a *string when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetAssigneeRole()(*string) {
    return m.assigneeRole
}
// GetDefaultValue gets the defaultValue property value. The defaultValue property
// returns a *string when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetDefaultValue()(*string) {
    return m.defaultValue
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["assigneeRole"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAssigneeRole(val)
        }
        return nil
    }
    res["defaultValue"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDefaultValue(val)
        }
        return nil
    }
    res["height"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHeight(val)
        }
        return nil
    }
    res["isReadOnly"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsReadOnly(val)
        }
        return nil
    }
    res["isRequired"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsRequired(val)
        }
        return nil
    }
    res["label"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLabel(val)
        }
        return nil
    }
    res["options"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateV1DocumentsItemFieldsItemWithFPutRequestBody_optionsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOptions(val.(V1DocumentsItemFieldsItemWithFPutRequestBody_optionsable))
        }
        return nil
    }
    res["order"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOrder(val)
        }
        return nil
    }
    res["pageNumber"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPageNumber(val)
        }
        return nil
    }
    res["width"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWidth(val)
        }
        return nil
    }
    res["x"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetX(val)
        }
        return nil
    }
    res["y"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetY(val)
        }
        return nil
    }
    return res
}
// GetHeight gets the height property value. The height property
// returns a *float64 when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetHeight()(*float64) {
    return m.height
}
// GetIsReadOnly gets the isReadOnly property value. The isReadOnly property
// returns a *bool when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetIsReadOnly()(*bool) {
    return m.isReadOnly
}
// GetIsRequired gets the isRequired property value. The isRequired property
// returns a *bool when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetIsRequired()(*bool) {
    return m.isRequired
}
// GetLabel gets the label property value. The label property
// returns a *string when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetLabel()(*string) {
    return m.label
}
// GetOptions gets the options property value. The options property
// returns a V1DocumentsItemFieldsItemWithFPutRequestBody_optionsable when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetOptions()(V1DocumentsItemFieldsItemWithFPutRequestBody_optionsable) {
    return m.options
}
// GetOrder gets the order property value. The order property
// returns a *int32 when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetOrder()(*int32) {
    return m.order
}
// GetPageNumber gets the pageNumber property value. The pageNumber property
// returns a *int32 when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetPageNumber()(*int32) {
    return m.pageNumber
}
// GetWidth gets the width property value. The width property
// returns a *float64 when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetWidth()(*float64) {
    return m.width
}
// GetX gets the x property value. The x property
// returns a *float64 when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetX()(*float64) {
    return m.x
}
// GetY gets the y property value. The y property
// returns a *float64 when successful
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) GetY()(*float64) {
    return m.y
}
// Serialize serializes information the current object
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("assigneeRole", m.GetAssigneeRole())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("defaultValue", m.GetDefaultValue())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("height", m.GetHeight())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isReadOnly", m.GetIsReadOnly())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isRequired", m.GetIsRequired())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("label", m.GetLabel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("options", m.GetOptions())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("order", m.GetOrder())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("pageNumber", m.GetPageNumber())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("width", m.GetWidth())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("x", m.GetX())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("y", m.GetY())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAssigneeRole sets the assigneeRole property value. The assigneeRole property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetAssigneeRole(value *string)() {
    m.assigneeRole = value
}
// SetDefaultValue sets the defaultValue property value. The defaultValue property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetDefaultValue(value *string)() {
    m.defaultValue = value
}
// SetHeight sets the height property value. The height property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetHeight(value *float64)() {
    m.height = value
}
// SetIsReadOnly sets the isReadOnly property value. The isReadOnly property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetIsReadOnly(value *bool)() {
    m.isReadOnly = value
}
// SetIsRequired sets the isRequired property value. The isRequired property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetIsRequired(value *bool)() {
    m.isRequired = value
}
// SetLabel sets the label property value. The label property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetLabel(value *string)() {
    m.label = value
}
// SetOptions sets the options property value. The options property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetOptions(value V1DocumentsItemFieldsItemWithFPutRequestBody_optionsable)() {
    m.options = value
}
// SetOrder sets the order property value. The order property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetOrder(value *int32)() {
    m.order = value
}
// SetPageNumber sets the pageNumber property value. The pageNumber property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetPageNumber(value *int32)() {
    m.pageNumber = value
}
// SetWidth sets the width property value. The width property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetWidth(value *float64)() {
    m.width = value
}
// SetX sets the x property value. The x property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetX(value *float64)() {
    m.x = value
}
// SetY sets the y property value. The y property
func (m *V1DocumentsItemFieldsItemWithFPutRequestBody) SetY(value *float64)() {
    m.y = value
}
type V1DocumentsItemFieldsItemWithFPutRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAssigneeRole()(*string)
    GetDefaultValue()(*string)
    GetHeight()(*float64)
    GetIsReadOnly()(*bool)
    GetIsRequired()(*bool)
    GetLabel()(*string)
    GetOptions()(V1DocumentsItemFieldsItemWithFPutRequestBody_optionsable)
    GetOrder()(*int32)
    GetPageNumber()(*int32)
    GetWidth()(*float64)
    GetX()(*float64)
    GetY()(*float64)
    SetAssigneeRole(value *string)()
    SetDefaultValue(value *string)()
    SetHeight(value *float64)()
    SetIsReadOnly(value *bool)()
    SetIsRequired(value *bool)()
    SetLabel(value *string)()
    SetOptions(value V1DocumentsItemFieldsItemWithFPutRequestBody_optionsable)()
    SetOrder(value *int32)()
    SetPageNumber(value *int32)()
    SetWidth(value *float64)()
    SetX(value *float64)()
    SetY(value *float64)()
}
