// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959 "github.com/Formalingo/sdk-go/client/models"
)

// V1DocumentsItemParseJobsItemApplyRequestBuilder builds and executes requests for operations under \api\v1\documents\{id}\parse-jobs\{jobId}\apply
type V1DocumentsItemParseJobsItemApplyRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1DocumentsItemParseJobsItemApplyRequestBuilderInternal instantiates a new V1DocumentsItemParseJobsItemApplyRequestBuilder and sets the default values.
func NewV1DocumentsItemParseJobsItemApplyRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemParseJobsItemApplyRequestBuilder) {
    m := &V1DocumentsItemParseJobsItemApplyRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v1/documents/{id}/parse-jobs/{jobId}/apply", pathParameters),
    }
    return m
}
// NewV1DocumentsItemParseJobsItemApplyRequestBuilder instantiates a new V1DocumentsItemParseJobsItemApplyRequestBuilder and sets the default values.
func NewV1DocumentsItemParseJobsItemApplyRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemParseJobsItemApplyRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1DocumentsItemParseJobsItemApplyRequestBuilderInternal(urlParams, requestAdapter)
}
// Post applies the detected fields from a completed preview parse job to the document draft. Requires the `documents:parse_ai` permission in addition to `write:documents`.
// returns a ApplyDocumentParseJobResponseable when successful
// returns a V1DocumentsItemParseJobsItemApplyDocumentParseJobResponse400Error error when the service returns a 400 status code
// returns a V1DocumentsItemParseJobsItemApplyDocumentParseJobResponse403Error error when the service returns a 403 status code
// returns a V1DocumentsItemParseJobsItemApplyDocumentParseJobResponse404Error error when the service returns a 404 status code
// returns a V1DocumentsItemParseJobsItemApplyDocumentParseJobResponse409Error error when the service returns a 409 status code
func (m *V1DocumentsItemParseJobsItemApplyRequestBuilder) Post(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.ApplyDocumentParseJobResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": CreateV1DocumentsItemParseJobsItemApplyDocumentParseJobResponse400ErrorFromDiscriminatorValue,
        "403": CreateV1DocumentsItemParseJobsItemApplyDocumentParseJobResponse403ErrorFromDiscriminatorValue,
        "404": CreateV1DocumentsItemParseJobsItemApplyDocumentParseJobResponse404ErrorFromDiscriminatorValue,
        "409": CreateV1DocumentsItemParseJobsItemApplyDocumentParseJobResponse409ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.CreateApplyDocumentParseJobResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.ApplyDocumentParseJobResponseable), nil
}
// ToPostRequestInformation applies the detected fields from a completed preview parse job to the document draft. Requires the `documents:parse_ai` permission in addition to `write:documents`.
// returns a *RequestInformation when successful
func (m *V1DocumentsItemParseJobsItemApplyRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1DocumentsItemParseJobsItemApplyRequestBuilder when successful
func (m *V1DocumentsItemParseJobsItemApplyRequestBuilder) WithUrl(rawUrl string)(*V1DocumentsItemParseJobsItemApplyRequestBuilder) {
    return NewV1DocumentsItemParseJobsItemApplyRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
