// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959 "github.com/Formalingo/sdk-go/client/models"
)

// V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder builds and executes requests for operations under \api\v1\documents\{id}\submissions\{sid}\signers\{signerId}
type V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilderInternal instantiates a new V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder and sets the default values.
func NewV1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder) {
    m := &V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v1/documents/{id}/submissions/{sid}/signers/{signerId}", pathParameters),
    }
    return m
}
// NewV1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder instantiates a new V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder and sets the default values.
func NewV1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete remove a signer
// returns a V1DocumentsItemSubmissionsItemSignersItemWithSignerDeleteResponseable when successful
func (m *V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(V1DocumentsItemSubmissionsItemSignersItemWithSignerDeleteResponseable, error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateV1DocumentsItemSubmissionsItemSignersItemWithSignerDeleteResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(V1DocumentsItemSubmissionsItemSignersItemWithSignerDeleteResponseable), nil
}
// Put update a signer
// returns a V1DocumentsItemSubmissionsItemSignersItemWithSignerPutResponseable when successful
// returns a ValidationError error when the service returns a 400 status code
func (m *V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder) Put(ctx context.Context, body id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.UpdateSignerBodyable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(V1DocumentsItemSubmissionsItemSignersItemWithSignerPutResponseable, error) {
    requestInfo, err := m.ToPutRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.CreateValidationErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateV1DocumentsItemSubmissionsItemSignersItemWithSignerPutResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(V1DocumentsItemSubmissionsItemSignersItemWithSignerPutResponseable), nil
}
// Responses the responses property
// returns a *V1DocumentsItemSubmissionsItemSignersItemResponsesRequestBuilder when successful
func (m *V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder) Responses()(*V1DocumentsItemSubmissionsItemSignersItemResponsesRequestBuilder) {
    return NewV1DocumentsItemSubmissionsItemSignersItemResponsesRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ToDeleteRequestInformation remove a signer
// returns a *RequestInformation when successful
func (m *V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToPutRequestInformation update a signer
// returns a *RequestInformation when successful
func (m *V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder) ToPutRequestInformation(ctx context.Context, body id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.UpdateSignerBodyable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.PUT, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder when successful
func (m *V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder) WithUrl(rawUrl string)(*V1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder) {
    return NewV1DocumentsItemSubmissionsItemSignersWithSignerItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
