// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f "client/models"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type V1DocumentsItemSubmissionsItemWithSGetResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The data property
    data iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentSubmissionable
    // The success property
    success *bool
}
// NewV1DocumentsItemSubmissionsItemWithSGetResponse instantiates a new V1DocumentsItemSubmissionsItemWithSGetResponse and sets the default values.
func NewV1DocumentsItemSubmissionsItemWithSGetResponse()(*V1DocumentsItemSubmissionsItemWithSGetResponse) {
    m := &V1DocumentsItemSubmissionsItemWithSGetResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateV1DocumentsItemSubmissionsItemWithSGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1DocumentsItemSubmissionsItemWithSGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1DocumentsItemSubmissionsItemWithSGetResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *V1DocumentsItemSubmissionsItemWithSGetResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetData gets the data property value. The data property
// returns a DocumentSubmissionable when successful
func (m *V1DocumentsItemSubmissionsItemWithSGetResponse) GetData()(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentSubmissionable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *V1DocumentsItemSubmissionsItemWithSGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.CreateDocumentSubmissionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetData(val.(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentSubmissionable))
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    return res
}
// GetSuccess gets the success property value. The success property
// returns a *bool when successful
func (m *V1DocumentsItemSubmissionsItemWithSGetResponse) GetSuccess()(*bool) {
    return m.success
}
// Serialize serializes information the current object
func (m *V1DocumentsItemSubmissionsItemWithSGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("data", m.GetData())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *V1DocumentsItemSubmissionsItemWithSGetResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetData sets the data property value. The data property
func (m *V1DocumentsItemSubmissionsItemWithSGetResponse) SetData(value iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentSubmissionable)() {
    m.data = value
}
// SetSuccess sets the success property value. The success property
func (m *V1DocumentsItemSubmissionsItemWithSGetResponse) SetSuccess(value *bool)() {
    m.success = value
}
type V1DocumentsItemSubmissionsItemWithSGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetData()(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentSubmissionable)
    GetSuccess()(*bool)
    SetData(value iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentSubmissionable)()
    SetSuccess(value *bool)()
}
