// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959 "github.com/Formalingo/sdk-go/client/models"
)

// V1DocumentsImportRequestBuilder builds and executes requests for operations under \api\v1\documents\import
type V1DocumentsImportRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1DocumentsImportRequestBuilderInternal instantiates a new V1DocumentsImportRequestBuilder and sets the default values.
func NewV1DocumentsImportRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsImportRequestBuilder) {
    m := &V1DocumentsImportRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v1/documents/import", pathParameters),
    }
    return m
}
// NewV1DocumentsImportRequestBuilder instantiates a new V1DocumentsImportRequestBuilder and sets the default values.
func NewV1DocumentsImportRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsImportRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1DocumentsImportRequestBuilderInternal(urlParams, requestAdapter)
}
// Post imports a .formalingo-doc bundle exported from another account. The import creates a new draft document with fields, signer roles, settings, and automation conditions. Integrations, automation actions, submissions, signers, responses, and deliveries are excluded.
// returns a ImportDocumentBundleResponseable when successful
// returns a V1DocumentsImportDocumentBundleResponse400Error error when the service returns a 400 status code
// returns a V1DocumentsImportDocumentBundleResponse402Error error when the service returns a 402 status code
// returns a V1DocumentsImportDocumentBundleResponse413Error error when the service returns a 413 status code
func (m *V1DocumentsImportRequestBuilder) Post(ctx context.Context, body i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.MultipartBody, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.ImportDocumentBundleResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": CreateV1DocumentsImportDocumentBundleResponse400ErrorFromDiscriminatorValue,
        "402": CreateV1DocumentsImportDocumentBundleResponse402ErrorFromDiscriminatorValue,
        "413": CreateV1DocumentsImportDocumentBundleResponse413ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.CreateImportDocumentBundleResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.ImportDocumentBundleResponseable), nil
}
// ToPostRequestInformation imports a .formalingo-doc bundle exported from another account. The import creates a new draft document with fields, signer roles, settings, and automation conditions. Integrations, automation actions, submissions, signers, responses, and deliveries are excluded.
// returns a *RequestInformation when successful
func (m *V1DocumentsImportRequestBuilder) ToPostRequestInformation(ctx context.Context, body i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.MultipartBody, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "multipart/form-data", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1DocumentsImportRequestBuilder when successful
func (m *V1DocumentsImportRequestBuilder) WithUrl(rawUrl string)(*V1DocumentsImportRequestBuilder) {
    return NewV1DocumentsImportRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
