// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1DocumentsItemSubmissionsWithSItemRequestBuilder builds and executes requests for operations under \api\v1\documents\{id}\submissions\{sid}
type V1DocumentsItemSubmissionsWithSItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1DocumentsItemSubmissionsWithSItemRequestBuilderInternal instantiates a new V1DocumentsItemSubmissionsWithSItemRequestBuilder and sets the default values.
func NewV1DocumentsItemSubmissionsWithSItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemSubmissionsWithSItemRequestBuilder) {
    m := &V1DocumentsItemSubmissionsWithSItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v1/documents/{id}/submissions/{sid}", pathParameters),
    }
    return m
}
// NewV1DocumentsItemSubmissionsWithSItemRequestBuilder instantiates a new V1DocumentsItemSubmissionsWithSItemRequestBuilder and sets the default values.
func NewV1DocumentsItemSubmissionsWithSItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemSubmissionsWithSItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1DocumentsItemSubmissionsWithSItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete delete a submission
// returns a V1DocumentsItemSubmissionsItemWithSDeleteResponseable when successful
func (m *V1DocumentsItemSubmissionsWithSItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(V1DocumentsItemSubmissionsItemWithSDeleteResponseable, error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateV1DocumentsItemSubmissionsItemWithSDeleteResponseFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(V1DocumentsItemSubmissionsItemWithSDeleteResponseable), nil
}
// Signers the signers property
// returns a *V1DocumentsItemSubmissionsItemSignersRequestBuilder when successful
func (m *V1DocumentsItemSubmissionsWithSItemRequestBuilder) Signers()(*V1DocumentsItemSubmissionsItemSignersRequestBuilder) {
    return NewV1DocumentsItemSubmissionsItemSignersRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ToDeleteRequestInformation delete a submission
// returns a *RequestInformation when successful
func (m *V1DocumentsItemSubmissionsWithSItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1DocumentsItemSubmissionsWithSItemRequestBuilder when successful
func (m *V1DocumentsItemSubmissionsWithSItemRequestBuilder) WithUrl(rawUrl string)(*V1DocumentsItemSubmissionsWithSItemRequestBuilder) {
    return NewV1DocumentsItemSubmissionsWithSItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
