// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1DocumentsItemRevisionsWithVersionItemRequestBuilder builds and executes requests for operations under \api\v1\documents\{id}\revisions\{version}
type V1DocumentsItemRevisionsWithVersionItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1DocumentsItemRevisionsWithVersionItemRequestBuilderInternal instantiates a new V1DocumentsItemRevisionsWithVersionItemRequestBuilder and sets the default values.
func NewV1DocumentsItemRevisionsWithVersionItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemRevisionsWithVersionItemRequestBuilder) {
    m := &V1DocumentsItemRevisionsWithVersionItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v1/documents/{id}/revisions/{version}", pathParameters),
    }
    return m
}
// NewV1DocumentsItemRevisionsWithVersionItemRequestBuilder instantiates a new V1DocumentsItemRevisionsWithVersionItemRequestBuilder and sets the default values.
func NewV1DocumentsItemRevisionsWithVersionItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1DocumentsItemRevisionsWithVersionItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1DocumentsItemRevisionsWithVersionItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Get get a document revision snapshot
// returns a V1DocumentsItemRevisionsItemWithVersionGetResponseable when successful
// returns a V1DocumentsItemRevisionsItemWithVersion404Error error when the service returns a 404 status code
func (m *V1DocumentsItemRevisionsWithVersionItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(V1DocumentsItemRevisionsItemWithVersionGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "404": CreateV1DocumentsItemRevisionsItemWithVersion404ErrorFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateV1DocumentsItemRevisionsItemWithVersionGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(V1DocumentsItemRevisionsItemWithVersionGetResponseable), nil
}
// ToGetRequestInformation get a document revision snapshot
// returns a *RequestInformation when successful
func (m *V1DocumentsItemRevisionsWithVersionItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V1DocumentsItemRevisionsWithVersionItemRequestBuilder when successful
func (m *V1DocumentsItemRevisionsWithVersionItemRequestBuilder) WithUrl(rawUrl string)(*V1DocumentsItemRevisionsWithVersionItemRequestBuilder) {
    return NewV1DocumentsItemRevisionsWithVersionItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
