// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f "client/models"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type V1DocumentsItemPublishPostResponse_data struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The document property
    document iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.Documentable
    // The revision property
    revision iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentRevisionable
}
// NewV1DocumentsItemPublishPostResponse_data instantiates a new V1DocumentsItemPublishPostResponse_data and sets the default values.
func NewV1DocumentsItemPublishPostResponse_data()(*V1DocumentsItemPublishPostResponse_data) {
    m := &V1DocumentsItemPublishPostResponse_data{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateV1DocumentsItemPublishPostResponse_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1DocumentsItemPublishPostResponse_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1DocumentsItemPublishPostResponse_data(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *V1DocumentsItemPublishPostResponse_data) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDocument gets the document property value. The document property
// returns a Documentable when successful
func (m *V1DocumentsItemPublishPostResponse_data) GetDocument()(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.Documentable) {
    return m.document
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *V1DocumentsItemPublishPostResponse_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["document"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.CreateDocumentFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDocument(val.(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.Documentable))
        }
        return nil
    }
    res["revision"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.CreateDocumentRevisionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRevision(val.(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentRevisionable))
        }
        return nil
    }
    return res
}
// GetRevision gets the revision property value. The revision property
// returns a DocumentRevisionable when successful
func (m *V1DocumentsItemPublishPostResponse_data) GetRevision()(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentRevisionable) {
    return m.revision
}
// Serialize serializes information the current object
func (m *V1DocumentsItemPublishPostResponse_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("document", m.GetDocument())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("revision", m.GetRevision())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *V1DocumentsItemPublishPostResponse_data) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDocument sets the document property value. The document property
func (m *V1DocumentsItemPublishPostResponse_data) SetDocument(value iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.Documentable)() {
    m.document = value
}
// SetRevision sets the revision property value. The revision property
func (m *V1DocumentsItemPublishPostResponse_data) SetRevision(value iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentRevisionable)() {
    m.revision = value
}
type V1DocumentsItemPublishPostResponse_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDocument()(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.Documentable)
    GetRevision()(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentRevisionable)
    SetDocument(value iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.Documentable)()
    SetRevision(value iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.DocumentRevisionable)()
}
