// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f "client/models"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type V1FormsItemRecipientsItemResponsesGetResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The data property
    data []iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.RecipientResponseable
    // The success property
    success *bool
}
// NewV1FormsItemRecipientsItemResponsesGetResponse instantiates a new V1FormsItemRecipientsItemResponsesGetResponse and sets the default values.
func NewV1FormsItemRecipientsItemResponsesGetResponse()(*V1FormsItemRecipientsItemResponsesGetResponse) {
    m := &V1FormsItemRecipientsItemResponsesGetResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateV1FormsItemRecipientsItemResponsesGetResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1FormsItemRecipientsItemResponsesGetResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1FormsItemRecipientsItemResponsesGetResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *V1FormsItemRecipientsItemResponsesGetResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetData gets the data property value. The data property
// returns a []RecipientResponseable when successful
func (m *V1FormsItemRecipientsItemResponsesGetResponse) GetData()([]iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.RecipientResponseable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *V1FormsItemRecipientsItemResponsesGetResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.CreateRecipientResponseFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.RecipientResponseable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.RecipientResponseable)
                }
            }
            m.SetData(res)
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    return res
}
// GetSuccess gets the success property value. The success property
// returns a *bool when successful
func (m *V1FormsItemRecipientsItemResponsesGetResponse) GetSuccess()(*bool) {
    return m.success
}
// Serialize serializes information the current object
func (m *V1FormsItemRecipientsItemResponsesGetResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetData() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetData()))
        for i, v := range m.GetData() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("data", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *V1FormsItemRecipientsItemResponsesGetResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetData sets the data property value. The data property
func (m *V1FormsItemRecipientsItemResponsesGetResponse) SetData(value []iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.RecipientResponseable)() {
    m.data = value
}
// SetSuccess sets the success property value. The success property
func (m *V1FormsItemRecipientsItemResponsesGetResponse) SetSuccess(value *bool)() {
    m.success = value
}
type V1FormsItemRecipientsItemResponsesGetResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetData()([]iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.RecipientResponseable)
    GetSuccess()(*bool)
    SetData(value []iaff47e4a4868373fab10f4216e997721eefe3df47195770f8e45cd166886968f.RecipientResponseable)()
    SetSuccess(value *bool)()
}
