// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959 "github.com/Formalingo/sdk-go/client/models"
)

type V1FormsItemPublishPostResponse_data struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The form property
    form id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.Formable
    // The revision property
    revision id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.FormRevisionable
}
// NewV1FormsItemPublishPostResponse_data instantiates a new V1FormsItemPublishPostResponse_data and sets the default values.
func NewV1FormsItemPublishPostResponse_data()(*V1FormsItemPublishPostResponse_data) {
    m := &V1FormsItemPublishPostResponse_data{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateV1FormsItemPublishPostResponse_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateV1FormsItemPublishPostResponse_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewV1FormsItemPublishPostResponse_data(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *V1FormsItemPublishPostResponse_data) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *V1FormsItemPublishPostResponse_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["form"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.CreateFormFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetForm(val.(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.Formable))
        }
        return nil
    }
    res["revision"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.CreateFormRevisionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRevision(val.(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.FormRevisionable))
        }
        return nil
    }
    return res
}
// GetForm gets the form property value. The form property
// returns a Formable when successful
func (m *V1FormsItemPublishPostResponse_data) GetForm()(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.Formable) {
    return m.form
}
// GetRevision gets the revision property value. The revision property
// returns a FormRevisionable when successful
func (m *V1FormsItemPublishPostResponse_data) GetRevision()(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.FormRevisionable) {
    return m.revision
}
// Serialize serializes information the current object
func (m *V1FormsItemPublishPostResponse_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("form", m.GetForm())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("revision", m.GetRevision())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *V1FormsItemPublishPostResponse_data) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetForm sets the form property value. The form property
func (m *V1FormsItemPublishPostResponse_data) SetForm(value id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.Formable)() {
    m.form = value
}
// SetRevision sets the revision property value. The revision property
func (m *V1FormsItemPublishPostResponse_data) SetRevision(value id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.FormRevisionable)() {
    m.revision = value
}
type V1FormsItemPublishPostResponse_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetForm()(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.Formable)
    GetRevision()(id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.FormRevisionable)
    SetForm(value id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.Formable)()
    SetRevision(value id2ed2db38d54d578f2dfa5a7b6fdf7691a3bc7147b2ff0c8ec851780edd5b959.FormRevisionable)()
}
