// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V1IntegrationsRequestBuilder builds and executes requests for operations under \api\v1\integrations
type V1IntegrationsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV1IntegrationsRequestBuilderInternal instantiates a new V1IntegrationsRequestBuilder and sets the default values.
func NewV1IntegrationsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1IntegrationsRequestBuilder) {
    m := &V1IntegrationsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v1/integrations", pathParameters),
    }
    return m
}
// NewV1IntegrationsRequestBuilder instantiates a new V1IntegrationsRequestBuilder and sets the default values.
func NewV1IntegrationsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V1IntegrationsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV1IntegrationsRequestBuilderInternal(urlParams, requestAdapter)
}
// Status the status property
// returns a *V1IntegrationsStatusRequestBuilder when successful
func (m *V1IntegrationsRequestBuilder) Status()(*V1IntegrationsStatusRequestBuilder) {
    return NewV1IntegrationsStatusRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
