// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type CreateFieldBody_direction int

const (
    AUTO_CREATEFIELDBODY_DIRECTION CreateFieldBody_direction = iota
    RTL_CREATEFIELDBODY_DIRECTION
    LTR_CREATEFIELDBODY_DIRECTION
)

func (i CreateFieldBody_direction) String() string {
    return []string{"auto", "rtl", "ltr"}[i]
}
func ParseCreateFieldBody_direction(v string) (any, error) {
    result := AUTO_CREATEFIELDBODY_DIRECTION
    switch v {
        case "auto":
            result = AUTO_CREATEFIELDBODY_DIRECTION
        case "rtl":
            result = RTL_CREATEFIELDBODY_DIRECTION
        case "ltr":
            result = LTR_CREATEFIELDBODY_DIRECTION
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeCreateFieldBody_direction(values []CreateFieldBody_direction) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i CreateFieldBody_direction) isMultiValue() bool {
    return false
}
