// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CreateQuestionBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The context property
    context *string
    // The is_pii property
    is_pii *bool
    // The is_required property
    is_required *bool
    // Type-specific options (choices, min/max, etc.)
    options i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // The order property
    order *int32
    // The priority property
    priority *CreateQuestionBody_priority
    // The question_text property
    question_text *string
    // Assign to a section (optional)
    section_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The type property
    typeEscaped *CreateQuestionBody_type
}
// NewCreateQuestionBody instantiates a new CreateQuestionBody and sets the default values.
func NewCreateQuestionBody()(*CreateQuestionBody) {
    m := &CreateQuestionBody{
    }
    m.SetAdditionalData(make(map[string]any))
    priorityValue := LOW_CREATEQUESTIONBODY_PRIORITY
    m.SetPriority(&priorityValue)
    return m
}
// CreateCreateQuestionBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCreateQuestionBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCreateQuestionBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CreateQuestionBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetContext gets the context property value. The context property
// returns a *string when successful
func (m *CreateQuestionBody) GetContext()(*string) {
    return m.context
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CreateQuestionBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["context"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetContext(val)
        }
        return nil
    }
    res["is_pii"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsPii(val)
        }
        return nil
    }
    res["is_required"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsRequired(val)
        }
        return nil
    }
    res["options"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOptions(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["order"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOrder(val)
        }
        return nil
    }
    res["priority"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseCreateQuestionBody_priority)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPriority(val.(*CreateQuestionBody_priority))
        }
        return nil
    }
    res["question_text"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetQuestionText(val)
        }
        return nil
    }
    res["section_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSectionId(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseCreateQuestionBody_type)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val.(*CreateQuestionBody_type))
        }
        return nil
    }
    return res
}
// GetIsPii gets the is_pii property value. The is_pii property
// returns a *bool when successful
func (m *CreateQuestionBody) GetIsPii()(*bool) {
    return m.is_pii
}
// GetIsRequired gets the is_required property value. The is_required property
// returns a *bool when successful
func (m *CreateQuestionBody) GetIsRequired()(*bool) {
    return m.is_required
}
// GetOptions gets the options property value. Type-specific options (choices, min/max, etc.)
// returns a UntypedNodeable when successful
func (m *CreateQuestionBody) GetOptions()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.options
}
// GetOrder gets the order property value. The order property
// returns a *int32 when successful
func (m *CreateQuestionBody) GetOrder()(*int32) {
    return m.order
}
// GetPriority gets the priority property value. The priority property
// returns a *CreateQuestionBody_priority when successful
func (m *CreateQuestionBody) GetPriority()(*CreateQuestionBody_priority) {
    return m.priority
}
// GetQuestionText gets the question_text property value. The question_text property
// returns a *string when successful
func (m *CreateQuestionBody) GetQuestionText()(*string) {
    return m.question_text
}
// GetSectionId gets the section_id property value. Assign to a section (optional)
// returns a *UUID when successful
func (m *CreateQuestionBody) GetSectionId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.section_id
}
// GetTypeEscaped gets the type property value. The type property
// returns a *CreateQuestionBody_type when successful
func (m *CreateQuestionBody) GetTypeEscaped()(*CreateQuestionBody_type) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *CreateQuestionBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("context", m.GetContext())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("is_pii", m.GetIsPii())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("is_required", m.GetIsRequired())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("options", m.GetOptions())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("order", m.GetOrder())
        if err != nil {
            return err
        }
    }
    if m.GetPriority() != nil {
        cast := (*m.GetPriority()).String()
        err := writer.WriteStringValue("priority", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("question_text", m.GetQuestionText())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("section_id", m.GetSectionId())
        if err != nil {
            return err
        }
    }
    if m.GetTypeEscaped() != nil {
        cast := (*m.GetTypeEscaped()).String()
        err := writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CreateQuestionBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetContext sets the context property value. The context property
func (m *CreateQuestionBody) SetContext(value *string)() {
    m.context = value
}
// SetIsPii sets the is_pii property value. The is_pii property
func (m *CreateQuestionBody) SetIsPii(value *bool)() {
    m.is_pii = value
}
// SetIsRequired sets the is_required property value. The is_required property
func (m *CreateQuestionBody) SetIsRequired(value *bool)() {
    m.is_required = value
}
// SetOptions sets the options property value. Type-specific options (choices, min/max, etc.)
func (m *CreateQuestionBody) SetOptions(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.options = value
}
// SetOrder sets the order property value. The order property
func (m *CreateQuestionBody) SetOrder(value *int32)() {
    m.order = value
}
// SetPriority sets the priority property value. The priority property
func (m *CreateQuestionBody) SetPriority(value *CreateQuestionBody_priority)() {
    m.priority = value
}
// SetQuestionText sets the question_text property value. The question_text property
func (m *CreateQuestionBody) SetQuestionText(value *string)() {
    m.question_text = value
}
// SetSectionId sets the section_id property value. Assign to a section (optional)
func (m *CreateQuestionBody) SetSectionId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.section_id = value
}
// SetTypeEscaped sets the type property value. The type property
func (m *CreateQuestionBody) SetTypeEscaped(value *CreateQuestionBody_type)() {
    m.typeEscaped = value
}
type CreateQuestionBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetContext()(*string)
    GetIsPii()(*bool)
    GetIsRequired()(*bool)
    GetOptions()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetOrder()(*int32)
    GetPriority()(*CreateQuestionBody_priority)
    GetQuestionText()(*string)
    GetSectionId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetTypeEscaped()(*CreateQuestionBody_type)
    SetContext(value *string)()
    SetIsPii(value *bool)()
    SetIsRequired(value *bool)()
    SetOptions(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetOrder(value *int32)()
    SetPriority(value *CreateQuestionBody_priority)()
    SetQuestionText(value *string)()
    SetSectionId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetTypeEscaped(value *CreateQuestionBody_type)()
}
