// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CreateSubmissionBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // One entry per signer role. Must provide all required roles.
    signers []SignerInputable
}
// NewCreateSubmissionBody instantiates a new CreateSubmissionBody and sets the default values.
func NewCreateSubmissionBody()(*CreateSubmissionBody) {
    m := &CreateSubmissionBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCreateSubmissionBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCreateSubmissionBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCreateSubmissionBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CreateSubmissionBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CreateSubmissionBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["signers"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateSignerInputFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]SignerInputable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(SignerInputable)
                }
            }
            m.SetSigners(res)
        }
        return nil
    }
    return res
}
// GetSigners gets the signers property value. One entry per signer role. Must provide all required roles.
// returns a []SignerInputable when successful
func (m *CreateSubmissionBody) GetSigners()([]SignerInputable) {
    return m.signers
}
// Serialize serializes information the current object
func (m *CreateSubmissionBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetSigners() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSigners()))
        for i, v := range m.GetSigners() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("signers", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CreateSubmissionBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetSigners sets the signers property value. One entry per signer role. Must provide all required roles.
func (m *CreateSubmissionBody) SetSigners(value []SignerInputable)() {
    m.signers = value
}
type CreateSubmissionBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetSigners()([]SignerInputable)
    SetSigners(value []SignerInputable)()
}
