// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type DetectedDocumentField_rect struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The height property
    height *float64
    // The width property
    width *float64
    // The x property
    x *float64
    // The y property
    y *float64
}
// NewDetectedDocumentField_rect instantiates a new DetectedDocumentField_rect and sets the default values.
func NewDetectedDocumentField_rect()(*DetectedDocumentField_rect) {
    m := &DetectedDocumentField_rect{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDetectedDocumentField_rectFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDetectedDocumentField_rectFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDetectedDocumentField_rect(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DetectedDocumentField_rect) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DetectedDocumentField_rect) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["height"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHeight(val)
        }
        return nil
    }
    res["width"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWidth(val)
        }
        return nil
    }
    res["x"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetX(val)
        }
        return nil
    }
    res["y"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetY(val)
        }
        return nil
    }
    return res
}
// GetHeight gets the height property value. The height property
// returns a *float64 when successful
func (m *DetectedDocumentField_rect) GetHeight()(*float64) {
    return m.height
}
// GetWidth gets the width property value. The width property
// returns a *float64 when successful
func (m *DetectedDocumentField_rect) GetWidth()(*float64) {
    return m.width
}
// GetX gets the x property value. The x property
// returns a *float64 when successful
func (m *DetectedDocumentField_rect) GetX()(*float64) {
    return m.x
}
// GetY gets the y property value. The y property
// returns a *float64 when successful
func (m *DetectedDocumentField_rect) GetY()(*float64) {
    return m.y
}
// Serialize serializes information the current object
func (m *DetectedDocumentField_rect) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteFloat64Value("height", m.GetHeight())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("width", m.GetWidth())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("x", m.GetX())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("y", m.GetY())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DetectedDocumentField_rect) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetHeight sets the height property value. The height property
func (m *DetectedDocumentField_rect) SetHeight(value *float64)() {
    m.height = value
}
// SetWidth sets the width property value. The width property
func (m *DetectedDocumentField_rect) SetWidth(value *float64)() {
    m.width = value
}
// SetX sets the x property value. The x property
func (m *DetectedDocumentField_rect) SetX(value *float64)() {
    m.x = value
}
// SetY sets the y property value. The y property
func (m *DetectedDocumentField_rect) SetY(value *float64)() {
    m.y = value
}
type DetectedDocumentField_rectable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetHeight()(*float64)
    GetWidth()(*float64)
    GetX()(*float64)
    GetY()(*float64)
    SetHeight(value *float64)()
    SetWidth(value *float64)()
    SetX(value *float64)()
    SetY(value *float64)()
}
