// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// DocumentSubmission_signedPdf stable API-key-gated file descriptor for the completed signed PDF.
type DocumentSubmission_signedPdf struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The authorization property
    authorization *DocumentSubmission_signedPdf_authorization
    // The contentType property
    contentType *string
    // The downloadMethod property
    downloadMethod *DocumentSubmission_signedPdf_downloadMethod
    // Formalingo API endpoint that requires Authorization: Bearer <api-key>
    downloadUrl *string
    // The fileId property
    fileId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The name property
    name *string
    // The sizeBytes property
    sizeBytes *int32
}
// NewDocumentSubmission_signedPdf instantiates a new DocumentSubmission_signedPdf and sets the default values.
func NewDocumentSubmission_signedPdf()(*DocumentSubmission_signedPdf) {
    m := &DocumentSubmission_signedPdf{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDocumentSubmission_signedPdfFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDocumentSubmission_signedPdfFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDocumentSubmission_signedPdf(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *DocumentSubmission_signedPdf) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAuthorization gets the authorization property value. The authorization property
// returns a *DocumentSubmission_signedPdf_authorization when successful
func (m *DocumentSubmission_signedPdf) GetAuthorization()(*DocumentSubmission_signedPdf_authorization) {
    return m.authorization
}
// GetContentType gets the contentType property value. The contentType property
// returns a *string when successful
func (m *DocumentSubmission_signedPdf) GetContentType()(*string) {
    return m.contentType
}
// GetDownloadMethod gets the downloadMethod property value. The downloadMethod property
// returns a *DocumentSubmission_signedPdf_downloadMethod when successful
func (m *DocumentSubmission_signedPdf) GetDownloadMethod()(*DocumentSubmission_signedPdf_downloadMethod) {
    return m.downloadMethod
}
// GetDownloadUrl gets the downloadUrl property value. Formalingo API endpoint that requires Authorization: Bearer <api-key>
// returns a *string when successful
func (m *DocumentSubmission_signedPdf) GetDownloadUrl()(*string) {
    return m.downloadUrl
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DocumentSubmission_signedPdf) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["authorization"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseDocumentSubmission_signedPdf_authorization)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAuthorization(val.(*DocumentSubmission_signedPdf_authorization))
        }
        return nil
    }
    res["contentType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetContentType(val)
        }
        return nil
    }
    res["downloadMethod"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseDocumentSubmission_signedPdf_downloadMethod)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDownloadMethod(val.(*DocumentSubmission_signedPdf_downloadMethod))
        }
        return nil
    }
    res["downloadUrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDownloadUrl(val)
        }
        return nil
    }
    res["fileId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFileId(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["sizeBytes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSizeBytes(val)
        }
        return nil
    }
    return res
}
// GetFileId gets the fileId property value. The fileId property
// returns a *UUID when successful
func (m *DocumentSubmission_signedPdf) GetFileId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.fileId
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *DocumentSubmission_signedPdf) GetName()(*string) {
    return m.name
}
// GetSizeBytes gets the sizeBytes property value. The sizeBytes property
// returns a *int32 when successful
func (m *DocumentSubmission_signedPdf) GetSizeBytes()(*int32) {
    return m.sizeBytes
}
// Serialize serializes information the current object
func (m *DocumentSubmission_signedPdf) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAuthorization() != nil {
        cast := (*m.GetAuthorization()).String()
        err := writer.WriteStringValue("authorization", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("contentType", m.GetContentType())
        if err != nil {
            return err
        }
    }
    if m.GetDownloadMethod() != nil {
        cast := (*m.GetDownloadMethod()).String()
        err := writer.WriteStringValue("downloadMethod", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("downloadUrl", m.GetDownloadUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("fileId", m.GetFileId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("sizeBytes", m.GetSizeBytes())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *DocumentSubmission_signedPdf) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAuthorization sets the authorization property value. The authorization property
func (m *DocumentSubmission_signedPdf) SetAuthorization(value *DocumentSubmission_signedPdf_authorization)() {
    m.authorization = value
}
// SetContentType sets the contentType property value. The contentType property
func (m *DocumentSubmission_signedPdf) SetContentType(value *string)() {
    m.contentType = value
}
// SetDownloadMethod sets the downloadMethod property value. The downloadMethod property
func (m *DocumentSubmission_signedPdf) SetDownloadMethod(value *DocumentSubmission_signedPdf_downloadMethod)() {
    m.downloadMethod = value
}
// SetDownloadUrl sets the downloadUrl property value. Formalingo API endpoint that requires Authorization: Bearer <api-key>
func (m *DocumentSubmission_signedPdf) SetDownloadUrl(value *string)() {
    m.downloadUrl = value
}
// SetFileId sets the fileId property value. The fileId property
func (m *DocumentSubmission_signedPdf) SetFileId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.fileId = value
}
// SetName sets the name property value. The name property
func (m *DocumentSubmission_signedPdf) SetName(value *string)() {
    m.name = value
}
// SetSizeBytes sets the sizeBytes property value. The sizeBytes property
func (m *DocumentSubmission_signedPdf) SetSizeBytes(value *int32)() {
    m.sizeBytes = value
}
type DocumentSubmission_signedPdfable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAuthorization()(*DocumentSubmission_signedPdf_authorization)
    GetContentType()(*string)
    GetDownloadMethod()(*DocumentSubmission_signedPdf_downloadMethod)
    GetDownloadUrl()(*string)
    GetFileId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetName()(*string)
    GetSizeBytes()(*int32)
    SetAuthorization(value *DocumentSubmission_signedPdf_authorization)()
    SetContentType(value *string)()
    SetDownloadMethod(value *DocumentSubmission_signedPdf_downloadMethod)()
    SetDownloadUrl(value *string)()
    SetFileId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetName(value *string)()
    SetSizeBytes(value *int32)()
}
