// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Document struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The completedPdfUrl property
    completedPdfUrl *string
    // The createdAt property
    createdAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The creatorId property
    creatorId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The deletedAt property
    deletedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The fileType property
    fileType *string
    // The id property
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The originalFilename property
    originalFilename *string
    // The originalUrl property
    originalUrl *string
    // The pageCount property
    pageCount *float64
    // The pageDimensions property
    pageDimensions []Document_pageDimensionsable
    // The status property
    status *Document_status
    // The title property
    title *string
    // The updatedAt property
    updatedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The workspaceId property
    workspaceId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
}
// NewDocument instantiates a new Document and sets the default values.
func NewDocument()(*Document) {
    m := &Document{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateDocumentFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDocumentFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewDocument(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Document) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCompletedPdfUrl gets the completedPdfUrl property value. The completedPdfUrl property
// returns a *string when successful
func (m *Document) GetCompletedPdfUrl()(*string) {
    return m.completedPdfUrl
}
// GetCreatedAt gets the createdAt property value. The createdAt property
// returns a *Time when successful
func (m *Document) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.createdAt
}
// GetCreatorId gets the creatorId property value. The creatorId property
// returns a *UUID when successful
func (m *Document) GetCreatorId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.creatorId
}
// GetDeletedAt gets the deletedAt property value. The deletedAt property
// returns a *Time when successful
func (m *Document) GetDeletedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.deletedAt
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Document) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["completedPdfUrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCompletedPdfUrl(val)
        }
        return nil
    }
    res["createdAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["creatorId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatorId(val)
        }
        return nil
    }
    res["deletedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDeletedAt(val)
        }
        return nil
    }
    res["fileType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFileType(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["originalFilename"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOriginalFilename(val)
        }
        return nil
    }
    res["originalUrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOriginalUrl(val)
        }
        return nil
    }
    res["pageCount"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPageCount(val)
        }
        return nil
    }
    res["pageDimensions"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateDocument_pageDimensionsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Document_pageDimensionsable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Document_pageDimensionsable)
                }
            }
            m.SetPageDimensions(res)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseDocument_status)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*Document_status))
        }
        return nil
    }
    res["title"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTitle(val)
        }
        return nil
    }
    res["updatedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    res["workspaceId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWorkspaceId(val)
        }
        return nil
    }
    return res
}
// GetFileType gets the fileType property value. The fileType property
// returns a *string when successful
func (m *Document) GetFileType()(*string) {
    return m.fileType
}
// GetId gets the id property value. The id property
// returns a *UUID when successful
func (m *Document) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetOriginalFilename gets the originalFilename property value. The originalFilename property
// returns a *string when successful
func (m *Document) GetOriginalFilename()(*string) {
    return m.originalFilename
}
// GetOriginalUrl gets the originalUrl property value. The originalUrl property
// returns a *string when successful
func (m *Document) GetOriginalUrl()(*string) {
    return m.originalUrl
}
// GetPageCount gets the pageCount property value. The pageCount property
// returns a *float64 when successful
func (m *Document) GetPageCount()(*float64) {
    return m.pageCount
}
// GetPageDimensions gets the pageDimensions property value. The pageDimensions property
// returns a []Document_pageDimensionsable when successful
func (m *Document) GetPageDimensions()([]Document_pageDimensionsable) {
    return m.pageDimensions
}
// GetStatus gets the status property value. The status property
// returns a *Document_status when successful
func (m *Document) GetStatus()(*Document_status) {
    return m.status
}
// GetTitle gets the title property value. The title property
// returns a *string when successful
func (m *Document) GetTitle()(*string) {
    return m.title
}
// GetUpdatedAt gets the updatedAt property value. The updatedAt property
// returns a *Time when successful
func (m *Document) GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.updatedAt
}
// GetWorkspaceId gets the workspaceId property value. The workspaceId property
// returns a *UUID when successful
func (m *Document) GetWorkspaceId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.workspaceId
}
// Serialize serializes information the current object
func (m *Document) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("completedPdfUrl", m.GetCompletedPdfUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("createdAt", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("creatorId", m.GetCreatorId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("deletedAt", m.GetDeletedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("fileType", m.GetFileType())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("originalFilename", m.GetOriginalFilename())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("originalUrl", m.GetOriginalUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("pageCount", m.GetPageCount())
        if err != nil {
            return err
        }
    }
    if m.GetPageDimensions() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetPageDimensions()))
        for i, v := range m.GetPageDimensions() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("pageDimensions", cast)
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("title", m.GetTitle())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("updatedAt", m.GetUpdatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("workspaceId", m.GetWorkspaceId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Document) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCompletedPdfUrl sets the completedPdfUrl property value. The completedPdfUrl property
func (m *Document) SetCompletedPdfUrl(value *string)() {
    m.completedPdfUrl = value
}
// SetCreatedAt sets the createdAt property value. The createdAt property
func (m *Document) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.createdAt = value
}
// SetCreatorId sets the creatorId property value. The creatorId property
func (m *Document) SetCreatorId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.creatorId = value
}
// SetDeletedAt sets the deletedAt property value. The deletedAt property
func (m *Document) SetDeletedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.deletedAt = value
}
// SetFileType sets the fileType property value. The fileType property
func (m *Document) SetFileType(value *string)() {
    m.fileType = value
}
// SetId sets the id property value. The id property
func (m *Document) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetOriginalFilename sets the originalFilename property value. The originalFilename property
func (m *Document) SetOriginalFilename(value *string)() {
    m.originalFilename = value
}
// SetOriginalUrl sets the originalUrl property value. The originalUrl property
func (m *Document) SetOriginalUrl(value *string)() {
    m.originalUrl = value
}
// SetPageCount sets the pageCount property value. The pageCount property
func (m *Document) SetPageCount(value *float64)() {
    m.pageCount = value
}
// SetPageDimensions sets the pageDimensions property value. The pageDimensions property
func (m *Document) SetPageDimensions(value []Document_pageDimensionsable)() {
    m.pageDimensions = value
}
// SetStatus sets the status property value. The status property
func (m *Document) SetStatus(value *Document_status)() {
    m.status = value
}
// SetTitle sets the title property value. The title property
func (m *Document) SetTitle(value *string)() {
    m.title = value
}
// SetUpdatedAt sets the updatedAt property value. The updatedAt property
func (m *Document) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.updatedAt = value
}
// SetWorkspaceId sets the workspaceId property value. The workspaceId property
func (m *Document) SetWorkspaceId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.workspaceId = value
}
type Documentable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCompletedPdfUrl()(*string)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetCreatorId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetDeletedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetFileType()(*string)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetOriginalFilename()(*string)
    GetOriginalUrl()(*string)
    GetPageCount()(*float64)
    GetPageDimensions()([]Document_pageDimensionsable)
    GetStatus()(*Document_status)
    GetTitle()(*string)
    GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetWorkspaceId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    SetCompletedPdfUrl(value *string)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetCreatorId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetDeletedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetFileType(value *string)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetOriginalFilename(value *string)()
    SetOriginalUrl(value *string)()
    SetPageCount(value *float64)()
    SetPageDimensions(value []Document_pageDimensionsable)()
    SetStatus(value *Document_status)()
    SetTitle(value *string)()
    SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetWorkspaceId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
}
