// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type DocumentSubmission_signedPdf_authorization int

const (
    BEARERFORMALINGOAPIKEY_DOCUMENTSUBMISSION_SIGNEDPDF_AUTHORIZATION DocumentSubmission_signedPdf_authorization = iota
)

func (i DocumentSubmission_signedPdf_authorization) String() string {
    return []string{"Bearer Formalingo API key"}[i]
}
func ParseDocumentSubmission_signedPdf_authorization(v string) (any, error) {
    result := BEARERFORMALINGOAPIKEY_DOCUMENTSUBMISSION_SIGNEDPDF_AUTHORIZATION
    switch v {
        case "Bearer Formalingo API key":
            result = BEARERFORMALINGOAPIKEY_DOCUMENTSUBMISSION_SIGNEDPDF_AUTHORIZATION
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeDocumentSubmission_signedPdf_authorization(values []DocumentSubmission_signedPdf_authorization) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i DocumentSubmission_signedPdf_authorization) isMultiValue() bool {
    return false
}
