// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type FileDescriptor_authorization int

const (
    BEARERFORMALINGOAPIKEY_FILEDESCRIPTOR_AUTHORIZATION FileDescriptor_authorization = iota
)

func (i FileDescriptor_authorization) String() string {
    return []string{"Bearer Formalingo API key"}[i]
}
func ParseFileDescriptor_authorization(v string) (any, error) {
    result := BEARERFORMALINGOAPIKEY_FILEDESCRIPTOR_AUTHORIZATION
    switch v {
        case "Bearer Formalingo API key":
            result = BEARERFORMALINGOAPIKEY_FILEDESCRIPTOR_AUTHORIZATION
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeFileDescriptor_authorization(values []FileDescriptor_authorization) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i FileDescriptor_authorization) isMultiValue() bool {
    return false
}
