// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type FileDescriptor_downloadMethod int

const (
    GET_FILEDESCRIPTOR_DOWNLOADMETHOD FileDescriptor_downloadMethod = iota
)

func (i FileDescriptor_downloadMethod) String() string {
    return []string{"GET"}[i]
}
func ParseFileDescriptor_downloadMethod(v string) (any, error) {
    result := GET_FILEDESCRIPTOR_DOWNLOADMETHOD
    switch v {
        case "GET":
            result = GET_FILEDESCRIPTOR_DOWNLOADMETHOD
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeFileDescriptor_downloadMethod(values []FileDescriptor_downloadMethod) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i FileDescriptor_downloadMethod) isMultiValue() bool {
    return false
}
