// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type Form_status int

const (
    DRAFT_FORM_STATUS Form_status = iota
    PUBLISHED_FORM_STATUS
    ARCHIVED_FORM_STATUS
)

func (i Form_status) String() string {
    return []string{"draft", "published", "archived"}[i]
}
func ParseForm_status(v string) (any, error) {
    result := DRAFT_FORM_STATUS
    switch v {
        case "draft":
            result = DRAFT_FORM_STATUS
        case "published":
            result = PUBLISHED_FORM_STATUS
        case "archived":
            result = ARCHIVED_FORM_STATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeForm_status(values []Form_status) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Form_status) isMultiValue() bool {
    return false
}
