// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type GetDocumentParseJobResponse_data_status int

const (
    PENDING_GETDOCUMENTPARSEJOBRESPONSE_DATA_STATUS GetDocumentParseJobResponse_data_status = iota
    PROCESSING_GETDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
    COMPLETED_GETDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
    FAILED_GETDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
)

func (i GetDocumentParseJobResponse_data_status) String() string {
    return []string{"pending", "processing", "completed", "failed"}[i]
}
func ParseGetDocumentParseJobResponse_data_status(v string) (any, error) {
    result := PENDING_GETDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
    switch v {
        case "pending":
            result = PENDING_GETDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
        case "processing":
            result = PROCESSING_GETDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
        case "completed":
            result = COMPLETED_GETDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
        case "failed":
            result = FAILED_GETDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeGetDocumentParseJobResponse_data_status(values []GetDocumentParseJobResponse_data_status) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i GetDocumentParseJobResponse_data_status) isMultiValue() bool {
    return false
}
