// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ImportDocumentBundleResponse struct {
    // The actions_omitted property
    actions_omitted *int32
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The conditions_omitted property
    conditions_omitted *int32
    // The data property
    data ImportDocumentBundleResponse_dataable
    // The meta property
    meta ImportDocumentBundleResponse_metaable
    // The success property
    success *bool
    // The warnings property
    warnings []string
}
// NewImportDocumentBundleResponse instantiates a new ImportDocumentBundleResponse and sets the default values.
func NewImportDocumentBundleResponse()(*ImportDocumentBundleResponse) {
    m := &ImportDocumentBundleResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateImportDocumentBundleResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateImportDocumentBundleResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewImportDocumentBundleResponse(), nil
}
// GetActionsOmitted gets the actions_omitted property value. The actions_omitted property
// returns a *int32 when successful
func (m *ImportDocumentBundleResponse) GetActionsOmitted()(*int32) {
    return m.actions_omitted
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ImportDocumentBundleResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetConditionsOmitted gets the conditions_omitted property value. The conditions_omitted property
// returns a *int32 when successful
func (m *ImportDocumentBundleResponse) GetConditionsOmitted()(*int32) {
    return m.conditions_omitted
}
// GetData gets the data property value. The data property
// returns a ImportDocumentBundleResponse_dataable when successful
func (m *ImportDocumentBundleResponse) GetData()(ImportDocumentBundleResponse_dataable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ImportDocumentBundleResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["actions_omitted"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetActionsOmitted(val)
        }
        return nil
    }
    res["conditions_omitted"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetConditionsOmitted(val)
        }
        return nil
    }
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateImportDocumentBundleResponse_dataFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetData(val.(ImportDocumentBundleResponse_dataable))
        }
        return nil
    }
    res["meta"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateImportDocumentBundleResponse_metaFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMeta(val.(ImportDocumentBundleResponse_metaable))
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    res["warnings"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetWarnings(res)
        }
        return nil
    }
    return res
}
// GetMeta gets the meta property value. The meta property
// returns a ImportDocumentBundleResponse_metaable when successful
func (m *ImportDocumentBundleResponse) GetMeta()(ImportDocumentBundleResponse_metaable) {
    return m.meta
}
// GetSuccess gets the success property value. The success property
// returns a *bool when successful
func (m *ImportDocumentBundleResponse) GetSuccess()(*bool) {
    return m.success
}
// GetWarnings gets the warnings property value. The warnings property
// returns a []string when successful
func (m *ImportDocumentBundleResponse) GetWarnings()([]string) {
    return m.warnings
}
// Serialize serializes information the current object
func (m *ImportDocumentBundleResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("actions_omitted", m.GetActionsOmitted())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("conditions_omitted", m.GetConditionsOmitted())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("data", m.GetData())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("meta", m.GetMeta())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    if m.GetWarnings() != nil {
        err := writer.WriteCollectionOfStringValues("warnings", m.GetWarnings())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetActionsOmitted sets the actions_omitted property value. The actions_omitted property
func (m *ImportDocumentBundleResponse) SetActionsOmitted(value *int32)() {
    m.actions_omitted = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ImportDocumentBundleResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetConditionsOmitted sets the conditions_omitted property value. The conditions_omitted property
func (m *ImportDocumentBundleResponse) SetConditionsOmitted(value *int32)() {
    m.conditions_omitted = value
}
// SetData sets the data property value. The data property
func (m *ImportDocumentBundleResponse) SetData(value ImportDocumentBundleResponse_dataable)() {
    m.data = value
}
// SetMeta sets the meta property value. The meta property
func (m *ImportDocumentBundleResponse) SetMeta(value ImportDocumentBundleResponse_metaable)() {
    m.meta = value
}
// SetSuccess sets the success property value. The success property
func (m *ImportDocumentBundleResponse) SetSuccess(value *bool)() {
    m.success = value
}
// SetWarnings sets the warnings property value. The warnings property
func (m *ImportDocumentBundleResponse) SetWarnings(value []string)() {
    m.warnings = value
}
type ImportDocumentBundleResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetActionsOmitted()(*int32)
    GetConditionsOmitted()(*int32)
    GetData()(ImportDocumentBundleResponse_dataable)
    GetMeta()(ImportDocumentBundleResponse_metaable)
    GetSuccess()(*bool)
    GetWarnings()([]string)
    SetActionsOmitted(value *int32)()
    SetConditionsOmitted(value *int32)()
    SetData(value ImportDocumentBundleResponse_dataable)()
    SetMeta(value ImportDocumentBundleResponse_metaable)()
    SetSuccess(value *bool)()
    SetWarnings(value []string)()
}
