// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ImportDocumentBundleResponse_data struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The generationType property
    generationType *ImportDocumentBundleResponse_data_generationType
    // The id property
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The originalFilename property
    originalFilename *string
    // The originalUrl property
    originalUrl *string
    // The status property
    status *ImportDocumentBundleResponse_data_status
    // The title property
    title *string
}
// NewImportDocumentBundleResponse_data instantiates a new ImportDocumentBundleResponse_data and sets the default values.
func NewImportDocumentBundleResponse_data()(*ImportDocumentBundleResponse_data) {
    m := &ImportDocumentBundleResponse_data{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateImportDocumentBundleResponse_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateImportDocumentBundleResponse_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewImportDocumentBundleResponse_data(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ImportDocumentBundleResponse_data) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ImportDocumentBundleResponse_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["generationType"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseImportDocumentBundleResponse_data_generationType)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetGenerationType(val.(*ImportDocumentBundleResponse_data_generationType))
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["originalFilename"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOriginalFilename(val)
        }
        return nil
    }
    res["originalUrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOriginalUrl(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseImportDocumentBundleResponse_data_status)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*ImportDocumentBundleResponse_data_status))
        }
        return nil
    }
    res["title"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTitle(val)
        }
        return nil
    }
    return res
}
// GetGenerationType gets the generationType property value. The generationType property
// returns a *ImportDocumentBundleResponse_data_generationType when successful
func (m *ImportDocumentBundleResponse_data) GetGenerationType()(*ImportDocumentBundleResponse_data_generationType) {
    return m.generationType
}
// GetId gets the id property value. The id property
// returns a *UUID when successful
func (m *ImportDocumentBundleResponse_data) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetOriginalFilename gets the originalFilename property value. The originalFilename property
// returns a *string when successful
func (m *ImportDocumentBundleResponse_data) GetOriginalFilename()(*string) {
    return m.originalFilename
}
// GetOriginalUrl gets the originalUrl property value. The originalUrl property
// returns a *string when successful
func (m *ImportDocumentBundleResponse_data) GetOriginalUrl()(*string) {
    return m.originalUrl
}
// GetStatus gets the status property value. The status property
// returns a *ImportDocumentBundleResponse_data_status when successful
func (m *ImportDocumentBundleResponse_data) GetStatus()(*ImportDocumentBundleResponse_data_status) {
    return m.status
}
// GetTitle gets the title property value. The title property
// returns a *string when successful
func (m *ImportDocumentBundleResponse_data) GetTitle()(*string) {
    return m.title
}
// Serialize serializes information the current object
func (m *ImportDocumentBundleResponse_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetGenerationType() != nil {
        cast := (*m.GetGenerationType()).String()
        err := writer.WriteStringValue("generationType", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("originalFilename", m.GetOriginalFilename())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("originalUrl", m.GetOriginalUrl())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("title", m.GetTitle())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ImportDocumentBundleResponse_data) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetGenerationType sets the generationType property value. The generationType property
func (m *ImportDocumentBundleResponse_data) SetGenerationType(value *ImportDocumentBundleResponse_data_generationType)() {
    m.generationType = value
}
// SetId sets the id property value. The id property
func (m *ImportDocumentBundleResponse_data) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetOriginalFilename sets the originalFilename property value. The originalFilename property
func (m *ImportDocumentBundleResponse_data) SetOriginalFilename(value *string)() {
    m.originalFilename = value
}
// SetOriginalUrl sets the originalUrl property value. The originalUrl property
func (m *ImportDocumentBundleResponse_data) SetOriginalUrl(value *string)() {
    m.originalUrl = value
}
// SetStatus sets the status property value. The status property
func (m *ImportDocumentBundleResponse_data) SetStatus(value *ImportDocumentBundleResponse_data_status)() {
    m.status = value
}
// SetTitle sets the title property value. The title property
func (m *ImportDocumentBundleResponse_data) SetTitle(value *string)() {
    m.title = value
}
type ImportDocumentBundleResponse_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetGenerationType()(*ImportDocumentBundleResponse_data_generationType)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetOriginalFilename()(*string)
    GetOriginalUrl()(*string)
    GetStatus()(*ImportDocumentBundleResponse_data_status)
    GetTitle()(*string)
    SetGenerationType(value *ImportDocumentBundleResponse_data_generationType)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetOriginalFilename(value *string)()
    SetOriginalUrl(value *string)()
    SetStatus(value *ImportDocumentBundleResponse_data_status)()
    SetTitle(value *string)()
}
