// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Stable phone-normalization failure code.
type PhoneValidationError_details_code int

const (
    MISSING_DEFAULT_COUNTRY_PHONEVALIDATIONERROR_DETAILS_CODE PhoneValidationError_details_code = iota
    INVALID_COUNTRY_PHONEVALIDATIONERROR_DETAILS_CODE
    INVALID_PHONE_PHONEVALIDATIONERROR_DETAILS_CODE
)

func (i PhoneValidationError_details_code) String() string {
    return []string{"missing_default_country", "invalid_country", "invalid_phone"}[i]
}
func ParsePhoneValidationError_details_code(v string) (any, error) {
    result := MISSING_DEFAULT_COUNTRY_PHONEVALIDATIONERROR_DETAILS_CODE
    switch v {
        case "missing_default_country":
            result = MISSING_DEFAULT_COUNTRY_PHONEVALIDATIONERROR_DETAILS_CODE
        case "invalid_country":
            result = INVALID_COUNTRY_PHONEVALIDATIONERROR_DETAILS_CODE
        case "invalid_phone":
            result = INVALID_PHONE_PHONEVALIDATIONERROR_DETAILS_CODE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializePhoneValidationError_details_code(values []PhoneValidationError_details_code) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i PhoneValidationError_details_code) isMultiValue() bool {
    return false
}
