// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type PhoneValidationDetails struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Stable phone-normalization failure code.
    code *PhoneValidationDetails_code
    // The invalid phone field. Indexed signer paths identify the failing signer.
    field *string
    // Zero-based signer index when a submission signer phone is invalid.
    index *int32
    // One-based import or bulk-recipient position when a phone is invalid.
    row *int32
}
// NewPhoneValidationDetails instantiates a new PhoneValidationDetails and sets the default values.
func NewPhoneValidationDetails()(*PhoneValidationDetails) {
    m := &PhoneValidationDetails{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePhoneValidationDetailsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePhoneValidationDetailsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPhoneValidationDetails(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PhoneValidationDetails) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCode gets the code property value. Stable phone-normalization failure code.
// returns a *PhoneValidationDetails_code when successful
func (m *PhoneValidationDetails) GetCode()(*PhoneValidationDetails_code) {
    return m.code
}
// GetField gets the field property value. The invalid phone field. Indexed signer paths identify the failing signer.
// returns a *string when successful
func (m *PhoneValidationDetails) GetField()(*string) {
    return m.field
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PhoneValidationDetails) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["code"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParsePhoneValidationDetails_code)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCode(val.(*PhoneValidationDetails_code))
        }
        return nil
    }
    res["field"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetField(val)
        }
        return nil
    }
    res["index"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIndex(val)
        }
        return nil
    }
    res["row"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRow(val)
        }
        return nil
    }
    return res
}
// GetIndex gets the index property value. Zero-based signer index when a submission signer phone is invalid.
// returns a *int32 when successful
func (m *PhoneValidationDetails) GetIndex()(*int32) {
    return m.index
}
// GetRow gets the row property value. One-based import or bulk-recipient position when a phone is invalid.
// returns a *int32 when successful
func (m *PhoneValidationDetails) GetRow()(*int32) {
    return m.row
}
// Serialize serializes information the current object
func (m *PhoneValidationDetails) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetCode() != nil {
        cast := (*m.GetCode()).String()
        err := writer.WriteStringValue("code", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("field", m.GetField())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("index", m.GetIndex())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("row", m.GetRow())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PhoneValidationDetails) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCode sets the code property value. Stable phone-normalization failure code.
func (m *PhoneValidationDetails) SetCode(value *PhoneValidationDetails_code)() {
    m.code = value
}
// SetField sets the field property value. The invalid phone field. Indexed signer paths identify the failing signer.
func (m *PhoneValidationDetails) SetField(value *string)() {
    m.field = value
}
// SetIndex sets the index property value. Zero-based signer index when a submission signer phone is invalid.
func (m *PhoneValidationDetails) SetIndex(value *int32)() {
    m.index = value
}
// SetRow sets the row property value. One-based import or bulk-recipient position when a phone is invalid.
func (m *PhoneValidationDetails) SetRow(value *int32)() {
    m.row = value
}
type PhoneValidationDetailsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCode()(*PhoneValidationDetails_code)
    GetField()(*string)
    GetIndex()(*int32)
    GetRow()(*int32)
    SetCode(value *PhoneValidationDetails_code)()
    SetField(value *string)()
    SetIndex(value *int32)()
    SetRow(value *int32)()
}
