// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Question struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The context property
    context *string
    // The createdAt property
    createdAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The formId property
    formId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The id property
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The isPii property
    isPii *bool
    // The isRequired property
    isRequired *bool
    // The options property
    options i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // The order property
    order *float64
    // The priority property
    priority *Question_priority
    // The questionText property
    questionText *string
    // The sectionId property
    sectionId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The type property
    typeEscaped *Question_type
}
// NewQuestion instantiates a new Question and sets the default values.
func NewQuestion()(*Question) {
    m := &Question{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateQuestionFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateQuestionFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewQuestion(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Question) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetContext gets the context property value. The context property
// returns a *string when successful
func (m *Question) GetContext()(*string) {
    return m.context
}
// GetCreatedAt gets the createdAt property value. The createdAt property
// returns a *Time when successful
func (m *Question) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.createdAt
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Question) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["context"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetContext(val)
        }
        return nil
    }
    res["createdAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["formId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFormId(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["isPii"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsPii(val)
        }
        return nil
    }
    res["isRequired"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsRequired(val)
        }
        return nil
    }
    res["options"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOptions(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["order"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOrder(val)
        }
        return nil
    }
    res["priority"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseQuestion_priority)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPriority(val.(*Question_priority))
        }
        return nil
    }
    res["questionText"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetQuestionText(val)
        }
        return nil
    }
    res["sectionId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSectionId(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseQuestion_type)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val.(*Question_type))
        }
        return nil
    }
    return res
}
// GetFormId gets the formId property value. The formId property
// returns a *UUID when successful
func (m *Question) GetFormId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.formId
}
// GetId gets the id property value. The id property
// returns a *UUID when successful
func (m *Question) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetIsPii gets the isPii property value. The isPii property
// returns a *bool when successful
func (m *Question) GetIsPii()(*bool) {
    return m.isPii
}
// GetIsRequired gets the isRequired property value. The isRequired property
// returns a *bool when successful
func (m *Question) GetIsRequired()(*bool) {
    return m.isRequired
}
// GetOptions gets the options property value. The options property
// returns a UntypedNodeable when successful
func (m *Question) GetOptions()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.options
}
// GetOrder gets the order property value. The order property
// returns a *float64 when successful
func (m *Question) GetOrder()(*float64) {
    return m.order
}
// GetPriority gets the priority property value. The priority property
// returns a *Question_priority when successful
func (m *Question) GetPriority()(*Question_priority) {
    return m.priority
}
// GetQuestionText gets the questionText property value. The questionText property
// returns a *string when successful
func (m *Question) GetQuestionText()(*string) {
    return m.questionText
}
// GetSectionId gets the sectionId property value. The sectionId property
// returns a *UUID when successful
func (m *Question) GetSectionId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.sectionId
}
// GetTypeEscaped gets the type property value. The type property
// returns a *Question_type when successful
func (m *Question) GetTypeEscaped()(*Question_type) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *Question) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("context", m.GetContext())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("createdAt", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("formId", m.GetFormId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isPii", m.GetIsPii())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("isRequired", m.GetIsRequired())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("options", m.GetOptions())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("order", m.GetOrder())
        if err != nil {
            return err
        }
    }
    if m.GetPriority() != nil {
        cast := (*m.GetPriority()).String()
        err := writer.WriteStringValue("priority", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("questionText", m.GetQuestionText())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("sectionId", m.GetSectionId())
        if err != nil {
            return err
        }
    }
    if m.GetTypeEscaped() != nil {
        cast := (*m.GetTypeEscaped()).String()
        err := writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Question) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetContext sets the context property value. The context property
func (m *Question) SetContext(value *string)() {
    m.context = value
}
// SetCreatedAt sets the createdAt property value. The createdAt property
func (m *Question) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.createdAt = value
}
// SetFormId sets the formId property value. The formId property
func (m *Question) SetFormId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.formId = value
}
// SetId sets the id property value. The id property
func (m *Question) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetIsPii sets the isPii property value. The isPii property
func (m *Question) SetIsPii(value *bool)() {
    m.isPii = value
}
// SetIsRequired sets the isRequired property value. The isRequired property
func (m *Question) SetIsRequired(value *bool)() {
    m.isRequired = value
}
// SetOptions sets the options property value. The options property
func (m *Question) SetOptions(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.options = value
}
// SetOrder sets the order property value. The order property
func (m *Question) SetOrder(value *float64)() {
    m.order = value
}
// SetPriority sets the priority property value. The priority property
func (m *Question) SetPriority(value *Question_priority)() {
    m.priority = value
}
// SetQuestionText sets the questionText property value. The questionText property
func (m *Question) SetQuestionText(value *string)() {
    m.questionText = value
}
// SetSectionId sets the sectionId property value. The sectionId property
func (m *Question) SetSectionId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.sectionId = value
}
// SetTypeEscaped sets the type property value. The type property
func (m *Question) SetTypeEscaped(value *Question_type)() {
    m.typeEscaped = value
}
type Questionable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetContext()(*string)
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetFormId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetIsPii()(*bool)
    GetIsRequired()(*bool)
    GetOptions()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetOrder()(*float64)
    GetPriority()(*Question_priority)
    GetQuestionText()(*string)
    GetSectionId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetTypeEscaped()(*Question_type)
    SetContext(value *string)()
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetFormId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetIsPii(value *bool)()
    SetIsRequired(value *bool)()
    SetOptions(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetOrder(value *float64)()
    SetPriority(value *Question_priority)()
    SetQuestionText(value *string)()
    SetSectionId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetTypeEscaped(value *Question_type)()
}
