// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type Question_priority int

const (
    LOW_QUESTION_PRIORITY Question_priority = iota
    MEDIUM_QUESTION_PRIORITY
    HIGH_QUESTION_PRIORITY
    CRITICAL_QUESTION_PRIORITY
)

func (i Question_priority) String() string {
    return []string{"low", "medium", "high", "critical"}[i]
}
func ParseQuestion_priority(v string) (any, error) {
    result := LOW_QUESTION_PRIORITY
    switch v {
        case "low":
            result = LOW_QUESTION_PRIORITY
        case "medium":
            result = MEDIUM_QUESTION_PRIORITY
        case "high":
            result = HIGH_QUESTION_PRIORITY
        case "critical":
            result = CRITICAL_QUESTION_PRIORITY
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeQuestion_priority(values []Question_priority) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Question_priority) isMultiValue() bool {
    return false
}
