// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type RecipientUpdate struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The created_at property
    created_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Included when the update service has an email value to return.
    email *string
    // The expires_at property
    expires_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The form_id property
    form_id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The has_password property
    has_password *bool
    // The id property
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The is_active property
    is_active *bool
    // The is_anonymous property
    is_anonymous *bool
    // The label property
    label *string
    // The last_activity_at property
    last_activity_at *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The link property
    link *string
    // Stored phone value; when phone is omitted, an untouched legacy value can be returned.
    phone *string
    // The response_count property
    response_count *float64
    // The status property
    status *RecipientUpdate_status
    // The token property
    token *string
    // The total_questions property
    total_questions *float64
    // The visit_count property
    visit_count *float64
}
// NewRecipientUpdate instantiates a new RecipientUpdate and sets the default values.
func NewRecipientUpdate()(*RecipientUpdate) {
    m := &RecipientUpdate{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateRecipientUpdateFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRecipientUpdateFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewRecipientUpdate(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RecipientUpdate) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCreatedAt gets the created_at property value. The created_at property
// returns a *Time when successful
func (m *RecipientUpdate) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.created_at
}
// GetEmail gets the email property value. Included when the update service has an email value to return.
// returns a *string when successful
func (m *RecipientUpdate) GetEmail()(*string) {
    return m.email
}
// GetExpiresAt gets the expires_at property value. The expires_at property
// returns a *Time when successful
func (m *RecipientUpdate) GetExpiresAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.expires_at
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RecipientUpdate) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["created_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["email"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmail(val)
        }
        return nil
    }
    res["expires_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetExpiresAt(val)
        }
        return nil
    }
    res["form_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFormId(val)
        }
        return nil
    }
    res["has_password"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHasPassword(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["is_active"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsActive(val)
        }
        return nil
    }
    res["is_anonymous"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsAnonymous(val)
        }
        return nil
    }
    res["label"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLabel(val)
        }
        return nil
    }
    res["last_activity_at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLastActivityAt(val)
        }
        return nil
    }
    res["link"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLink(val)
        }
        return nil
    }
    res["phone"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPhone(val)
        }
        return nil
    }
    res["response_count"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResponseCount(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseRecipientUpdate_status)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*RecipientUpdate_status))
        }
        return nil
    }
    res["token"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetToken(val)
        }
        return nil
    }
    res["total_questions"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotalQuestions(val)
        }
        return nil
    }
    res["visit_count"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVisitCount(val)
        }
        return nil
    }
    return res
}
// GetFormId gets the form_id property value. The form_id property
// returns a *UUID when successful
func (m *RecipientUpdate) GetFormId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.form_id
}
// GetHasPassword gets the has_password property value. The has_password property
// returns a *bool when successful
func (m *RecipientUpdate) GetHasPassword()(*bool) {
    return m.has_password
}
// GetId gets the id property value. The id property
// returns a *UUID when successful
func (m *RecipientUpdate) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetIsActive gets the is_active property value. The is_active property
// returns a *bool when successful
func (m *RecipientUpdate) GetIsActive()(*bool) {
    return m.is_active
}
// GetIsAnonymous gets the is_anonymous property value. The is_anonymous property
// returns a *bool when successful
func (m *RecipientUpdate) GetIsAnonymous()(*bool) {
    return m.is_anonymous
}
// GetLabel gets the label property value. The label property
// returns a *string when successful
func (m *RecipientUpdate) GetLabel()(*string) {
    return m.label
}
// GetLastActivityAt gets the last_activity_at property value. The last_activity_at property
// returns a *Time when successful
func (m *RecipientUpdate) GetLastActivityAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.last_activity_at
}
// GetLink gets the link property value. The link property
// returns a *string when successful
func (m *RecipientUpdate) GetLink()(*string) {
    return m.link
}
// GetPhone gets the phone property value. Stored phone value; when phone is omitted, an untouched legacy value can be returned.
// returns a *string when successful
func (m *RecipientUpdate) GetPhone()(*string) {
    return m.phone
}
// GetResponseCount gets the response_count property value. The response_count property
// returns a *float64 when successful
func (m *RecipientUpdate) GetResponseCount()(*float64) {
    return m.response_count
}
// GetStatus gets the status property value. The status property
// returns a *RecipientUpdate_status when successful
func (m *RecipientUpdate) GetStatus()(*RecipientUpdate_status) {
    return m.status
}
// GetToken gets the token property value. The token property
// returns a *string when successful
func (m *RecipientUpdate) GetToken()(*string) {
    return m.token
}
// GetTotalQuestions gets the total_questions property value. The total_questions property
// returns a *float64 when successful
func (m *RecipientUpdate) GetTotalQuestions()(*float64) {
    return m.total_questions
}
// GetVisitCount gets the visit_count property value. The visit_count property
// returns a *float64 when successful
func (m *RecipientUpdate) GetVisitCount()(*float64) {
    return m.visit_count
}
// Serialize serializes information the current object
func (m *RecipientUpdate) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteTimeValue("created_at", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("email", m.GetEmail())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("expires_at", m.GetExpiresAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("form_id", m.GetFormId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("has_password", m.GetHasPassword())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("is_active", m.GetIsActive())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("is_anonymous", m.GetIsAnonymous())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("label", m.GetLabel())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("last_activity_at", m.GetLastActivityAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("link", m.GetLink())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("phone", m.GetPhone())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("response_count", m.GetResponseCount())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("token", m.GetToken())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("total_questions", m.GetTotalQuestions())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("visit_count", m.GetVisitCount())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RecipientUpdate) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCreatedAt sets the created_at property value. The created_at property
func (m *RecipientUpdate) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.created_at = value
}
// SetEmail sets the email property value. Included when the update service has an email value to return.
func (m *RecipientUpdate) SetEmail(value *string)() {
    m.email = value
}
// SetExpiresAt sets the expires_at property value. The expires_at property
func (m *RecipientUpdate) SetExpiresAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.expires_at = value
}
// SetFormId sets the form_id property value. The form_id property
func (m *RecipientUpdate) SetFormId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.form_id = value
}
// SetHasPassword sets the has_password property value. The has_password property
func (m *RecipientUpdate) SetHasPassword(value *bool)() {
    m.has_password = value
}
// SetId sets the id property value. The id property
func (m *RecipientUpdate) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetIsActive sets the is_active property value. The is_active property
func (m *RecipientUpdate) SetIsActive(value *bool)() {
    m.is_active = value
}
// SetIsAnonymous sets the is_anonymous property value. The is_anonymous property
func (m *RecipientUpdate) SetIsAnonymous(value *bool)() {
    m.is_anonymous = value
}
// SetLabel sets the label property value. The label property
func (m *RecipientUpdate) SetLabel(value *string)() {
    m.label = value
}
// SetLastActivityAt sets the last_activity_at property value. The last_activity_at property
func (m *RecipientUpdate) SetLastActivityAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.last_activity_at = value
}
// SetLink sets the link property value. The link property
func (m *RecipientUpdate) SetLink(value *string)() {
    m.link = value
}
// SetPhone sets the phone property value. Stored phone value; when phone is omitted, an untouched legacy value can be returned.
func (m *RecipientUpdate) SetPhone(value *string)() {
    m.phone = value
}
// SetResponseCount sets the response_count property value. The response_count property
func (m *RecipientUpdate) SetResponseCount(value *float64)() {
    m.response_count = value
}
// SetStatus sets the status property value. The status property
func (m *RecipientUpdate) SetStatus(value *RecipientUpdate_status)() {
    m.status = value
}
// SetToken sets the token property value. The token property
func (m *RecipientUpdate) SetToken(value *string)() {
    m.token = value
}
// SetTotalQuestions sets the total_questions property value. The total_questions property
func (m *RecipientUpdate) SetTotalQuestions(value *float64)() {
    m.total_questions = value
}
// SetVisitCount sets the visit_count property value. The visit_count property
func (m *RecipientUpdate) SetVisitCount(value *float64)() {
    m.visit_count = value
}
type RecipientUpdateable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetEmail()(*string)
    GetExpiresAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetFormId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetHasPassword()(*bool)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetIsActive()(*bool)
    GetIsAnonymous()(*bool)
    GetLabel()(*string)
    GetLastActivityAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetLink()(*string)
    GetPhone()(*string)
    GetResponseCount()(*float64)
    GetStatus()(*RecipientUpdate_status)
    GetToken()(*string)
    GetTotalQuestions()(*float64)
    GetVisitCount()(*float64)
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetEmail(value *string)()
    SetExpiresAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetFormId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetHasPassword(value *bool)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetIsActive(value *bool)()
    SetIsAnonymous(value *bool)()
    SetLabel(value *string)()
    SetLastActivityAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetLink(value *string)()
    SetPhone(value *string)()
    SetResponseCount(value *float64)()
    SetStatus(value *RecipientUpdate_status)()
    SetToken(value *string)()
    SetTotalQuestions(value *float64)()
    SetVisitCount(value *float64)()
}
