// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type StartDocumentParseJobResponse_data struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The documentId property
    documentId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The parseJobId property
    parseJobId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // The pollAfterMs property
    pollAfterMs *int32
    // The status property
    status *StartDocumentParseJobResponse_data_status
}
// NewStartDocumentParseJobResponse_data instantiates a new StartDocumentParseJobResponse_data and sets the default values.
func NewStartDocumentParseJobResponse_data()(*StartDocumentParseJobResponse_data) {
    m := &StartDocumentParseJobResponse_data{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateStartDocumentParseJobResponse_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateStartDocumentParseJobResponse_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewStartDocumentParseJobResponse_data(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *StartDocumentParseJobResponse_data) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDocumentId gets the documentId property value. The documentId property
// returns a *UUID when successful
func (m *StartDocumentParseJobResponse_data) GetDocumentId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.documentId
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *StartDocumentParseJobResponse_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["documentId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDocumentId(val)
        }
        return nil
    }
    res["parseJobId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetParseJobId(val)
        }
        return nil
    }
    res["pollAfterMs"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPollAfterMs(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseStartDocumentParseJobResponse_data_status)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val.(*StartDocumentParseJobResponse_data_status))
        }
        return nil
    }
    return res
}
// GetParseJobId gets the parseJobId property value. The parseJobId property
// returns a *UUID when successful
func (m *StartDocumentParseJobResponse_data) GetParseJobId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.parseJobId
}
// GetPollAfterMs gets the pollAfterMs property value. The pollAfterMs property
// returns a *int32 when successful
func (m *StartDocumentParseJobResponse_data) GetPollAfterMs()(*int32) {
    return m.pollAfterMs
}
// GetStatus gets the status property value. The status property
// returns a *StartDocumentParseJobResponse_data_status when successful
func (m *StartDocumentParseJobResponse_data) GetStatus()(*StartDocumentParseJobResponse_data_status) {
    return m.status
}
// Serialize serializes information the current object
func (m *StartDocumentParseJobResponse_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteUUIDValue("documentId", m.GetDocumentId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("parseJobId", m.GetParseJobId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("pollAfterMs", m.GetPollAfterMs())
        if err != nil {
            return err
        }
    }
    if m.GetStatus() != nil {
        cast := (*m.GetStatus()).String()
        err := writer.WriteStringValue("status", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *StartDocumentParseJobResponse_data) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDocumentId sets the documentId property value. The documentId property
func (m *StartDocumentParseJobResponse_data) SetDocumentId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.documentId = value
}
// SetParseJobId sets the parseJobId property value. The parseJobId property
func (m *StartDocumentParseJobResponse_data) SetParseJobId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.parseJobId = value
}
// SetPollAfterMs sets the pollAfterMs property value. The pollAfterMs property
func (m *StartDocumentParseJobResponse_data) SetPollAfterMs(value *int32)() {
    m.pollAfterMs = value
}
// SetStatus sets the status property value. The status property
func (m *StartDocumentParseJobResponse_data) SetStatus(value *StartDocumentParseJobResponse_data_status)() {
    m.status = value
}
type StartDocumentParseJobResponse_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDocumentId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetParseJobId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetPollAfterMs()(*int32)
    GetStatus()(*StartDocumentParseJobResponse_data_status)
    SetDocumentId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetParseJobId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetPollAfterMs(value *int32)()
    SetStatus(value *StartDocumentParseJobResponse_data_status)()
}
