// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type StartDocumentParseJobResponse_data_status int

const (
    PENDING_STARTDOCUMENTPARSEJOBRESPONSE_DATA_STATUS StartDocumentParseJobResponse_data_status = iota
    PROCESSING_STARTDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
    COMPLETED_STARTDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
    FAILED_STARTDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
)

func (i StartDocumentParseJobResponse_data_status) String() string {
    return []string{"pending", "processing", "completed", "failed"}[i]
}
func ParseStartDocumentParseJobResponse_data_status(v string) (any, error) {
    result := PENDING_STARTDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
    switch v {
        case "pending":
            result = PENDING_STARTDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
        case "processing":
            result = PROCESSING_STARTDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
        case "completed":
            result = COMPLETED_STARTDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
        case "failed":
            result = FAILED_STARTDOCUMENTPARSEJOBRESPONSE_DATA_STATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeStartDocumentParseJobResponse_data_status(values []StartDocumentParseJobResponse_data_status) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i StartDocumentParseJobResponse_data_status) isMultiValue() bool {
    return false
}
