// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SubmissionPdf struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The completedAt property
    completedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Presigned download URL. Expires in 5 minutes.
    downloadUrl *string
    // URL expiry in seconds
    expiresIn *float64
    // The submissionId property
    submissionId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
}
// NewSubmissionPdf instantiates a new SubmissionPdf and sets the default values.
func NewSubmissionPdf()(*SubmissionPdf) {
    m := &SubmissionPdf{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateSubmissionPdfFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSubmissionPdfFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSubmissionPdf(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SubmissionPdf) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCompletedAt gets the completedAt property value. The completedAt property
// returns a *Time when successful
func (m *SubmissionPdf) GetCompletedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.completedAt
}
// GetDownloadUrl gets the downloadUrl property value. Presigned download URL. Expires in 5 minutes.
// returns a *string when successful
func (m *SubmissionPdf) GetDownloadUrl()(*string) {
    return m.downloadUrl
}
// GetExpiresIn gets the expiresIn property value. URL expiry in seconds
// returns a *float64 when successful
func (m *SubmissionPdf) GetExpiresIn()(*float64) {
    return m.expiresIn
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SubmissionPdf) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["completedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCompletedAt(val)
        }
        return nil
    }
    res["downloadUrl"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDownloadUrl(val)
        }
        return nil
    }
    res["expiresIn"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetFloat64Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetExpiresIn(val)
        }
        return nil
    }
    res["submissionId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSubmissionId(val)
        }
        return nil
    }
    return res
}
// GetSubmissionId gets the submissionId property value. The submissionId property
// returns a *UUID when successful
func (m *SubmissionPdf) GetSubmissionId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.submissionId
}
// Serialize serializes information the current object
func (m *SubmissionPdf) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteTimeValue("completedAt", m.GetCompletedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("downloadUrl", m.GetDownloadUrl())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteFloat64Value("expiresIn", m.GetExpiresIn())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("submissionId", m.GetSubmissionId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SubmissionPdf) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCompletedAt sets the completedAt property value. The completedAt property
func (m *SubmissionPdf) SetCompletedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.completedAt = value
}
// SetDownloadUrl sets the downloadUrl property value. Presigned download URL. Expires in 5 minutes.
func (m *SubmissionPdf) SetDownloadUrl(value *string)() {
    m.downloadUrl = value
}
// SetExpiresIn sets the expiresIn property value. URL expiry in seconds
func (m *SubmissionPdf) SetExpiresIn(value *float64)() {
    m.expiresIn = value
}
// SetSubmissionId sets the submissionId property value. The submissionId property
func (m *SubmissionPdf) SetSubmissionId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.submissionId = value
}
type SubmissionPdfable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCompletedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetDownloadUrl()(*string)
    GetExpiresIn()(*float64)
    GetSubmissionId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    SetCompletedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetDownloadUrl(value *string)()
    SetExpiresIn(value *float64)()
    SetSubmissionId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
}
