// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type UpdateFormBody_status int

const (
    DRAFT_UPDATEFORMBODY_STATUS UpdateFormBody_status = iota
    PUBLISHED_UPDATEFORMBODY_STATUS
    ARCHIVED_UPDATEFORMBODY_STATUS
)

func (i UpdateFormBody_status) String() string {
    return []string{"draft", "published", "archived"}[i]
}
func ParseUpdateFormBody_status(v string) (any, error) {
    result := DRAFT_UPDATEFORMBODY_STATUS
    switch v {
        case "draft":
            result = DRAFT_UPDATEFORMBODY_STATUS
        case "published":
            result = PUBLISHED_UPDATEFORMBODY_STATUS
        case "archived":
            result = ARCHIVED_UPDATEFORMBODY_STATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeUpdateFormBody_status(values []UpdateFormBody_status) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i UpdateFormBody_status) isMultiValue() bool {
    return false
}
