// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type UpdateRecipientResponsesBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Map of question ID → new value. Performs upsert on Response records.
    responses UpdateRecipientResponsesBody_responsesable
}
// NewUpdateRecipientResponsesBody instantiates a new UpdateRecipientResponsesBody and sets the default values.
func NewUpdateRecipientResponsesBody()(*UpdateRecipientResponsesBody) {
    m := &UpdateRecipientResponsesBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateUpdateRecipientResponsesBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateUpdateRecipientResponsesBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewUpdateRecipientResponsesBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *UpdateRecipientResponsesBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *UpdateRecipientResponsesBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["responses"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateUpdateRecipientResponsesBody_responsesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResponses(val.(UpdateRecipientResponsesBody_responsesable))
        }
        return nil
    }
    return res
}
// GetResponses gets the responses property value. Map of question ID → new value. Performs upsert on Response records.
// returns a UpdateRecipientResponsesBody_responsesable when successful
func (m *UpdateRecipientResponsesBody) GetResponses()(UpdateRecipientResponsesBody_responsesable) {
    return m.responses
}
// Serialize serializes information the current object
func (m *UpdateRecipientResponsesBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("responses", m.GetResponses())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *UpdateRecipientResponsesBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetResponses sets the responses property value. Map of question ID → new value. Performs upsert on Response records.
func (m *UpdateRecipientResponsesBody) SetResponses(value UpdateRecipientResponsesBody_responsesable)() {
    m.responses = value
}
type UpdateRecipientResponsesBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetResponses()(UpdateRecipientResponsesBody_responsesable)
    SetResponses(value UpdateRecipientResponsesBody_responsesable)()
}
