// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package item
type WithFPutRequestBody_direction int

const (
    AUTO_WITHFPUTREQUESTBODY_DIRECTION WithFPutRequestBody_direction = iota
    RTL_WITHFPUTREQUESTBODY_DIRECTION
    LTR_WITHFPUTREQUESTBODY_DIRECTION
)

func (i WithFPutRequestBody_direction) String() string {
    return []string{"auto", "rtl", "ltr"}[i]
}
func ParseWithFPutRequestBody_direction(v string) (any, error) {
    result := AUTO_WITHFPUTREQUESTBODY_DIRECTION
    switch v {
        case "auto":
            result = AUTO_WITHFPUTREQUESTBODY_DIRECTION
        case "rtl":
            result = RTL_WITHFPUTREQUESTBODY_DIRECTION
        case "ltr":
            result = LTR_WITHFPUTREQUESTBODY_DIRECTION
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeWithFPutRequestBody_direction(values []WithFPutRequestBody_direction) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i WithFPutRequestBody_direction) isMultiValue() bool {
    return false
}
